<?php if (!empty($this->files)): ?>
<br />
<h1><?php __e('Downloads') ?></h1>
<?php foreach ($this->files as $file): /* @var $file SoftsaleFile */?>
<div class="softsale-file">
    <span class="softsale-file-title"><?php p($file->title) ?></span>
    <span class="softsale-file-versions">
        <select size="1" class="softsale-file-version-select">
            <option value=""><?php __e('choose a version')?></option>
            <?php echo Am_Controller::renderOptions(renderUploadsOptions($file->getUploads(true))); ?>
        </select>
    </span>
    <?php foreach ($file->getUploads(true) as $upload): ?>
    <div class="softsale-file-version-detail" style="display:none;" data-version="<?php p($upload->version)?>">
    <em><?php echo renderUploadTitle($upload); ?></em> 
    <a href="<?php p(renderUploadLink($file, $upload))?>"><?php __e('download')?></a>
    <?php if ($upload->details): ?><div class="softsale-file-version-detail-details"><?php echo $upload->details?></div><?php endif ?>
    </div>
    <?php endforeach ?>
</div>
<?php endforeach; endif ?>

<style type="text/css">
    .softsale-file-version-select { font-size: xx-small; border: none; background-color: transparent; }
    .softsale-file { padding-bottom: 1em; }
    .softsale-file-version-detail {
        border: solid 1px gray;
        max-height: 1em;
        overflow-y: scroll;
    }
    .softsale-file-version-detail-details { 
        white-space: pre; 
        font-size: xx-small; 
        font-style: italic; 
        color: darkcyan;
    }
</style>

<script type="text/javascript">
jQuery(function($){
    $("select.softsale-file-version-select").change(function(){
        var version = $(this).val();
        var details = $(this).closest(".softsale-file").find(".softsale-file-version-detail");
        details.hide().filter("[data-version='"+version+"']").show();
    });
});
</script>

<?php 
function renderUploadTitle(SoftsaleFileUpload $upload)
{
    return $upload->version . ' (' . amDate($upload->date) . ') - ' . $upload->desc;
}
/**
 * @param SoftsaleFileUpload[] $uploads
 */
function renderUploadsOptions(array $uploads)
{
    $ret = array();
    foreach ($uploads as $upload)
    {
        $ret[$upload->version] = renderUploadTitle($upload);
    }
    return $ret;
}
function renderUploadLink(SoftsaleFile $file, SoftsaleFileUpload $upload)
{
    return REL_ROOT_URL . '/softsale/download/?file_id=' . $file->pk() . '&file_upload_id=' . $upload->pk();
}
?>