<?xml version="1.0" encoding="UTF-8"?>
<CONFIG>
  <Makefile Value="2"/>
  <Params Value=" -Fu.;C:/lazarus/packager/units/$(CPU_TARGET)-$(OS_TARGET) -Fi.  -MObjFPC -Scghi -O1 -g -gl -l -vewnhibq copycat.pas"/>
</CONFIG>
