; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define protected
#define FullSource
#define SetupName "CopyCat_FullSource"
#define README_FILE "..\License\Readme_reg.txt"
#define LICENSE_FILE "..\License\License_reg.txt"
#include "CopyCat.iss"
