#define IDH_HTML_Introduction                              0x00000000 // Introduction
#define IDH_HTML_Getting_started                           0x00000001 // Getting started
#define IDH_HTML_Replication_nodes                         0x00000002 // Replication nodes
#define IDH_HTML_Conflict_management                       0x00000003 // Conflict management
#define IDH_HTML_Database_tables                           0x00000004 // Database tables
#define IDH_HTML_RPL_LOG                                   0x00000005 // RPL$LOG
#define IDH_HTML_RPL_USERS                                 0x00000006 // RPL$USERS
#define IDH_HTML_RPL_CONFLICTS                             0x00000007 // RPL$CONFLICTS
#define IDH_HTML_RPL_TABLES                                0x00000008 // RPL$TABLES
#define IDH_HTML_RPL_PROCEDURES                            0x00000009 // RPL$PROCEDURES
#define IDH_HTML_RPL_ERRORS                                0x0000000A // RPL$ERRORS
#define IDH_HTML_RPL_TRACE                                 0x0000000B // RPL$TRACE
#define IDH_HTML_RPL_LOG_VALUES                            0x0000000C // RPL$LOG_VALUES
#define IDH_HTML_ECcLostConnection                         0x0000000D // ECcLostConnection
#define IDH_HTML_ECcLostConnection_Connection              0x0000000E // ECcLostConnection.Connection
#define IDH_HTML_ECcLostConnection_Create_TCcConnection    0x0000000F // ECcLostConnection.Create@TCcConnection
#define IDH_HTML_ECcReplicationAborted                     0x00000010 // ECcReplicationAborted
#define IDH_HTML_ECcReplicationAborted_Replicator          0x00000011 // ECcReplicationAborted.Replicator
#define IDH_HTML_ECcReplicationAborted_Create_TCcReplicator 0x00000012 // ECcReplicationAborted.Create@TCcReplicator
#define IDH_HTML_EReplError                                0x00000013 // EReplError
#define IDH_HTML_TAutoRepl                                 0x00000014 // TAutoRepl
#define IDH_HTML_TAutoRepl_Enabled                         0x00000015 // TAutoRepl.Enabled
#define IDH_HTML_TCcAbstractQueryObject                    0x00000016 // TCcAbstractQueryObject
#define IDH_HTML_TCcAbstractQueryObject_Query              0x00000017 // TCcAbstractQueryObject.Query
#define IDH_HTML_TCcAbstractQueryObject_SelectStatement    0x00000018 // TCcAbstractQueryObject.SelectStatement
#define IDH_HTML_TCcAbstractQueryObject_Create_TCcConnection_TCcQuery_Integer_Boolean 0x00000019 // TCcAbstractQueryObject.Create@TCcConnection@TCcQuery@Integer@Boolean
#define IDH_HTML_TCcArray                                  0x0000001A // TCcArray
#define IDH_HTML_TCcArray_Count                            0x0000001B // TCcArray.Count
#define IDH_HTML_TCcArray_Value                            0x0000001C // TCcArray.Value
#define IDH_HTML_TCcArray_Add                              0x0000001D // TCcArray.Add
#define IDH_HTML_TCcArray_AddValue_TCcValue                0x0000001E // TCcArray.AddValue@TCcValue
#define IDH_HTML_TCcArray_Clear                            0x0000001F // TCcArray.Clear
#define IDH_HTML_TCcArray_Create                           0x00000020 // TCcArray.Create
#define IDH_HTML_TCcArray_Destroy                          0x00000021 // TCcArray.Destroy
#define IDH_HTML_TCcAutoCommit                             0x00000022 // TCcAutoCommit
#define IDH_HTML_TCcAutoCommit_CommitType                  0x00000023 // TCcAutoCommit.CommitType
#define IDH_HTML_TCcClientTransport                        0x00000024 // TCcClientTransport
#define IDH_HTML_TCcClientTransport_AutoCommit             0x00000025 // TCcClientTransport.AutoCommit
#define IDH_HTML_TCcClientTransport_DatabaseAlias          0x00000026 // TCcClientTransport.DatabaseAlias
#define IDH_HTML_TCcClientTransport_KeepAliveInterval      0x00000027 // TCcClientTransport.KeepAliveInterval
#define IDH_HTML_TCcClientTransport_Password               0x00000028 // TCcClientTransport.Password
#define IDH_HTML_TCcClientTransport_ServerCopyCatVersion   0x00000029 // TCcClientTransport.ServerCopyCatVersion
#define IDH_HTML_TCcClientTransport_SessionActive          0x0000002A // TCcClientTransport.SessionActive
#define IDH_HTML_TCcClientTransport_Create_TComponent      0x0000002B // TCcClientTransport.Create@TComponent
#define IDH_HTML_TCcClientTransport_Destroy                0x0000002C // TCcClientTransport.Destroy
#define IDH_HTML_TCcConfig                                 0x0000002D // TCcConfig
#define IDH_HTML_TCcConfig_ConfigName                      0x0000002E // TCcConfig.ConfigName
#define IDH_HTML_TCcConfig_Connection                      0x0000002F // TCcConfig.Connection
#define IDH_HTML_TCcConfig_FailIfNoPK                      0x00000030 // TCcConfig.FailIfNoPK
#define IDH_HTML_TCcConfig_Nodes                           0x00000031 // TCcConfig.Nodes
#define IDH_HTML_TCcConfig_OnQueryReady                    0x00000032 // TCcConfig.OnQueryReady
#define IDH_HTML_TCcConfig_OnScriptReady                   0x00000033 // TCcConfig.OnScriptReady
#define IDH_HTML_TCcConfig_Script                          0x00000034 // TCcConfig.Script
#define IDH_HTML_TCcConfig_Tables                          0x00000035 // TCcConfig.Tables
#define IDH_HTML_TCcConfig_TrackFieldChanges               0x00000036 // TCcConfig.TrackFieldChanges
#define IDH_HTML_TCcConfig_Version                         0x00000037 // TCcConfig.Version
#define IDH_HTML_TCcConfig_Connect                         0x00000038 // TCcConfig.Connect
#define IDH_HTML_TCcConfig_ConnectAndRemoveConfig          0x00000039 // TCcConfig.ConnectAndRemoveConfig
#define IDH_HTML_TCcConfig_Create_TComponent               0x0000003A // TCcConfig.Create@TComponent
#define IDH_HTML_TCcConfig_Destroy                         0x0000003B // TCcConfig.Destroy
#define IDH_HTML_TCcConfig_Disconnect                      0x0000003C // TCcConfig.Disconnect
#define IDH_HTML_TCcConfig_GenerateConfig                  0x0000003D // TCcConfig.GenerateConfig
#define IDH_HTML_TCcConfig_GenerateTriggers_String         0x0000003E // TCcConfig.GenerateTriggers@String
#define IDH_HTML_TCcConfig_GetGenerator_String_Integer     0x0000003F // TCcConfig.GetGenerator@String@Integer
#define IDH_HTML_TCcConfig_PrepareBatchImport_String_String_String 0x00000040 // TCcConfig.PrepareBatchImport@String@String@String
#define IDH_HTML_TCcConfig_RemoveTriggers_String           0x00000041 // TCcConfig.RemoveTriggers@String
#define IDH_HTML_TCcConfig_TableNameWithConfig_String      0x00000042 // TCcConfig.TableNameWithConfig@String
#define IDH_HTML_TCcConfigTable                            0x00000043 // TCcConfigTable
#define IDH_HTML_TCcConfigTable_Condition                  0x00000044 // TCcConfigTable.Condition
#define IDH_HTML_TCcConfigTable_DeleteCondition            0x00000045 // TCcConfigTable.DeleteCondition
#define IDH_HTML_TCcConfigTable_FieldsExcluded             0x00000046 // TCcConfigTable.FieldsExcluded
#define IDH_HTML_TCcConfigTable_FieldsIncluded             0x00000047 // TCcConfigTable.FieldsIncluded
#define IDH_HTML_TCcConfigTable_InsertCondition            0x00000048 // TCcConfigTable.InsertCondition
#define IDH_HTML_TCcConfigTable_PKSyncStatements           0x00000049 // TCcConfigTable.PKSyncStatements
#define IDH_HTML_TCcConfigTable_Priority                   0x0000004A // TCcConfigTable.Priority
#define IDH_HTML_TCcConfigTable_SyncFieldNames             0x0000004B // TCcConfigTable.SyncFieldNames
#define IDH_HTML_TCcConfigTable_SyncStatements             0x0000004C // TCcConfigTable.SyncStatements
#define IDH_HTML_TCcConfigTable_TableName                  0x0000004D // TCcConfigTable.TableName
#define IDH_HTML_TCcConfigTable_UpdateCondition            0x0000004E // TCcConfigTable.UpdateCondition
#define IDH_HTML_TCcConfigTable_Create_TCollection         0x0000004F // TCcConfigTable.Create@TCollection
#define IDH_HTML_TCcConfigTable_Destroy                    0x00000050 // TCcConfigTable.Destroy
#define IDH_HTML_TCcConfigTables                           0x00000051 // TCcConfigTables
#define IDH_HTML_TCcConfigTables_Item                      0x00000052 // TCcConfigTables.Item
#define IDH_HTML_TCcConfigTables_Add                       0x00000053 // TCcConfigTables.Add
#define IDH_HTML_TCcConfigTables_Create_TPersistent        0x00000054 // TCcConfigTables.Create@TPersistent
#define IDH_HTML_TCcConfigTables_FindTable_String          0x00000055 // TCcConfigTables.FindTable@String
#define IDH_HTML_TCcConflictMgr                            0x00000056 // TCcConflictMgr
#define IDH_HTML_TCcConnection                             0x00000057 // TCcConnection
#define IDH_HTML_TCcConnection_CanUseRowsAffected          0x00000058 // TCcConnection.CanUseRowsAffected
#define IDH_HTML_TCcConnection_Connected                   0x00000059 // TCcConnection.Connected
#define IDH_HTML_TCcConnection_ConnectionParams            0x0000005A // TCcConnection.ConnectionParams
#define IDH_HTML_TCcConnection_DBAdaptor                   0x0000005B // TCcConnection.DBAdaptor
#define IDH_HTML_TCcConnection_DBName                      0x0000005C // TCcConnection.DBName
#define IDH_HTML_TCcConnection_DBType                      0x0000005D // TCcConnection.DBType
#define IDH_HTML_TCcConnection_DBVersion                   0x0000005E // TCcConnection.DBVersion
#define IDH_HTML_TCcConnection_DDLQuery                    0x0000005F // TCcConnection.DDLQuery
#define IDH_HTML_TCcConnection_InTransaction               0x00000060 // TCcConnection.InTransaction
#define IDH_HTML_TCcConnection_OnConnectionLost            0x00000061 // TCcConnection.OnConnectionLost
#define IDH_HTML_TCcConnection_OnDestroyQueries            0x00000062 // TCcConnection.OnDestroyQueries
#define IDH_HTML_TCcConnection_OnQueryExecute              0x00000063 // TCcConnection.OnQueryExecute
#define IDH_HTML_TCcConnection_ReplicatingNode             0x00000064 // TCcConnection.ReplicatingNode
#define IDH_HTML_TCcConnection_ReplicatingNodePassword     0x00000065 // TCcConnection.ReplicatingNodePassword
#define IDH_HTML_TCcConnection_SelectQuery                 0x00000066 // TCcConnection.SelectQuery
#define IDH_HTML_TCcConnection_UpdateQuery                 0x00000067 // TCcConnection.UpdateQuery
#define IDH_HTML_TCcConnection_Assign_TPersistent          0x00000068 // TCcConnection.Assign@TPersistent
#define IDH_HTML_TCcConnection_CheckDisconnected           0x00000069 // TCcConnection.CheckDisconnected
#define IDH_HTML_TCcConnection_ClearQueries                0x0000006A // TCcConnection.ClearQueries
#define IDH_HTML_TCcConnection_Commit                      0x0000006B // TCcConnection.Commit
#define IDH_HTML_TCcConnection_CommitRetaining             0x0000006C // TCcConnection.CommitRetaining
#define IDH_HTML_TCcConnection_Connect                     0x0000006D // TCcConnection.Connect
#define IDH_HTML_TCcConnection_ConnectAsNode_string_string 0x0000006E // TCcConnection.ConnectAsNode@string@string
#define IDH_HTML_TCcConnection_ConnectorName               0x0000006F // TCcConnection.ConnectorName
#define IDH_HTML_TCcConnection_Create_TComponent           0x00000070 // TCcConnection.Create@TComponent
#define IDH_HTML_TCcConnection_DatabaseTypes_TStrings      0x00000071 // TCcConnection.DatabaseTypes@TStrings
#define IDH_HTML_TCcConnection_DatabaseVersions_TStrings   0x00000072 // TCcConnection.DatabaseVersions@TStrings
#define IDH_HTML_TCcConnection_Destroy                     0x00000073 // TCcConnection.Destroy
#define IDH_HTML_TCcConnection_Disconnect                  0x00000074 // TCcConnection.Disconnect
#define IDH_HTML_TCcConnection_ExecQuery_string            0x00000075 // TCcConnection.ExecQuery@string
#define IDH_HTML_TCcConnection_FindQuery_string            0x00000076 // TCcConnection.FindQuery@string
#define IDH_HTML_TCcConnection_Gen_Id_string_Integer       0x00000077 // TCcConnection.Gen_Id@string@Integer
#define IDH_HTML_TCcConnection_GetFieldType_string_string  0x00000078 // TCcConnection.GetFieldType@string@string
#define IDH_HTML_TCcConnection_ListAllProcedures           0x00000079 // TCcConnection.ListAllProcedures
#define IDH_HTML_TCcConnection_ListAllTables               0x0000007A // TCcConnection.ListAllTables
#define IDH_HTML_TCcConnection_ListFieldsForNoPK_string    0x0000007B // TCcConnection.ListFieldsForNoPK@string
#define IDH_HTML_TCcConnection_ListGenerators              0x0000007C // TCcConnection.ListGenerators
#define IDH_HTML_TCcConnection_ListKeywordsForbiddenAsFieldNames 0x0000007D // TCcConnection.ListKeywordsForbiddenAsFieldNames
#define IDH_HTML_TCcConnection_ListPrimaryKeys_string      0x0000007E // TCcConnection.ListPrimaryKeys@string
#define IDH_HTML_TCcConnection_ListProcedures              0x0000007F // TCcConnection.ListProcedures
#define IDH_HTML_TCcConnection_ListTableFields_string      0x00000080 // TCcConnection.ListTableFields@string
#define IDH_HTML_TCcConnection_ListTables                  0x00000081 // TCcConnection.ListTables
#define IDH_HTML_TCcConnection_ListTriggers                0x00000082 // TCcConnection.ListTriggers
#define IDH_HTML_TCcConnection_ListUpdatableTableFields_string 0x00000083 // TCcConnection.ListUpdatableTableFields@string
#define IDH_HTML_TCcConnection_Loaded                      0x00000084 // TCcConnection.Loaded
#define IDH_HTML_TCcConnection_MaxDDLNameLength            0x00000085 // TCcConnection.MaxDDLNameLength
#define IDH_HTML_TCcConnection_RefreshNodes                0x00000086 // TCcConnection.RefreshNodes
#define IDH_HTML_TCcConnection_Rollback                    0x00000087 // TCcConnection.Rollback
#define IDH_HTML_TCcConnection_RollbackRetaining           0x00000088 // TCcConnection.RollbackRetaining
#define IDH_HTML_TCcConnection_StartTransaction            0x00000089 // TCcConnection.StartTransaction
#define IDH_HTML_TCcCustomConflictMgr                      0x0000008A // TCcCustomConflictMgr
#define IDH_HTML_TCcCustomLog                              0x0000008B // TCcCustomLog
#define IDH_HTML_TCcCustomLog_AllowedOperations            0x0000008C // TCcCustomLog.AllowedOperations
#define IDH_HTML_TCcCustomLog_CurrentLine                  0x0000008D // TCcCustomLog.CurrentLine
#define IDH_HTML_TCcCustomLog_Dest                         0x0000008E // TCcCustomLog.Dest
#define IDH_HTML_TCcCustomLog_Eof                          0x0000008F // TCcCustomLog.Eof
#define IDH_HTML_TCcCustomLog_Keys                         0x00000090 // TCcCustomLog.Keys
#define IDH_HTML_TCcCustomLog_LineCount                    0x00000091 // TCcCustomLog.LineCount
#define IDH_HTML_TCcCustomLog_LocalMode                    0x00000092 // TCcCustomLog.LocalMode
#define IDH_HTML_TCcCustomLog_OldRecordID                  0x00000093 // TCcCustomLog.OldRecordID
#define IDH_HTML_TCcCustomLog_Origin                       0x00000094 // TCcCustomLog.Origin
#define IDH_HTML_TCcCustomLog_PrimaryKeys                  0x00000095 // TCcCustomLog.PrimaryKeys
#define IDH_HTML_TCcCustomLog_RecordID                     0x00000096 // TCcCustomLog.RecordID
#define IDH_HTML_TCcCustomLog_RemoteTableName              0x00000097 // TCcCustomLog.RemoteTableName
#define IDH_HTML_TCcCustomLog_TableName                    0x00000098 // TCcCustomLog.TableName
#define IDH_HTML_TCcCustomLog_FBN_string                   0x00000099 // TCcCustomLog.FBN@string
#define IDH_HTML_TCcCustomLog_FieldByName_string           0x0000009A // TCcCustomLog.FieldByName@string
#define IDH_HTML_TCcCustomLog_FieldExists_string           0x0000009B // TCcCustomLog.FieldExists@string
#define IDH_HTML_TCcCustomLog_Next                         0x0000009C // TCcCustomLog.Next
#define IDH_HTML_TCcDataSet                                0x0000009D // TCcDataSet
#define IDH_HTML_TCcDataSet_Active                         0x0000009E // TCcDataSet.Active
#define IDH_HTML_TCcDataSet_Connection                     0x0000009F // TCcDataSet.Connection
#define IDH_HTML_TCcDataSet_DeleteQuery                    0x000000A0 // TCcDataSet.DeleteQuery
#define IDH_HTML_TCcDataSet_InsertQuery                    0x000000A1 // TCcDataSet.InsertQuery
#define IDH_HTML_TCcDataSet_RefreshQuery                   0x000000A2 // TCcDataSet.RefreshQuery
#define IDH_HTML_TCcDataSet_RowsAffected                   0x000000A3 // TCcDataSet.RowsAffected
#define IDH_HTML_TCcDataSet_SelectQuery                    0x000000A4 // TCcDataSet.SelectQuery
#define IDH_HTML_TCcDataSet_SQL                            0x000000A5 // TCcDataSet.SQL
#define IDH_HTML_TCcDataSet_SQLDelete                      0x000000A6 // TCcDataSet.SQLDelete
#define IDH_HTML_TCcDataSet_SQLInsert                      0x000000A7 // TCcDataSet.SQLInsert
#define IDH_HTML_TCcDataSet_SQLRefresh                     0x000000A8 // TCcDataSet.SQLRefresh
#define IDH_HTML_TCcDataSet_SQLUpdate                      0x000000A9 // TCcDataSet.SQLUpdate
#define IDH_HTML_TCcDataSet_UpdateQuery                    0x000000AA // TCcDataSet.UpdateQuery
#define IDH_HTML_TCcDataSet_CopyCurrentRecord_TCcRecord    0x000000AB // TCcDataSet.CopyCurrentRecord@TCcRecord
#define IDH_HTML_TCcDataSet_Create_TComponent              0x000000AC // TCcDataSet.Create@TComponent
#define IDH_HTML_TCcDataSet_Destroy                        0x000000AD // TCcDataSet.Destroy
#define IDH_HTML_TCcDBAdaptor                              0x000000AE // TCcDBAdaptor
#define IDH_HTML_TCcDBAdaptor_CurrentTimeStampSQL          0x000000AF // TCcDBAdaptor.CurrentTimeStampSQL
#define IDH_HTML_TCcDBAdaptor_QuoteMetadata                0x000000B0 // TCcDBAdaptor.QuoteMetadata
#define IDH_HTML_TCcDBAdaptor_SupportedVersions            0x000000B1 // TCcDBAdaptor.SupportedVersions
#define IDH_HTML_TCcDBAdaptor_UseRowsAffected              0x000000B2 // TCcDBAdaptor.UseRowsAffected
#define IDH_HTML_TCcDBAdaptor_Version                      0x000000B3 // TCcDBAdaptor.Version
#define IDH_HTML_TCcDBAdaptor_CheckCustomMetadata          0x000000B4 // TCcDBAdaptor.CheckCustomMetadata
#define IDH_HTML_TCcDBAdaptor_CheckExtraCustomMetadata     0x000000B5 // TCcDBAdaptor.CheckExtraCustomMetadata
#define IDH_HTML_TCcDBAdaptor_ConvertValue_Variant_TFieldType 0x000000B6 // TCcDBAdaptor.ConvertValue@Variant@TFieldType
#define IDH_HTML_TCcDBAdaptor_Create_TCcConnection         0x000000B7 // TCcDBAdaptor.Create@TCcConnection
#define IDH_HTML_TCcDBAdaptor_CreateProcedures             0x000000B8 // TCcDBAdaptor.CreateProcedures
#define IDH_HTML_TCcDBAdaptor_DeclareField_string_TFieldType_Integer_Boolean_Boolean_Boolean 0x000000B9 // TCcDBAdaptor.DeclareField@string@TFieldType@Integer@Boolean@Boolean@Boolean
#define IDH_HTML_TCcDBAdaptor_DeclareGenerator_string      0x000000BA // TCcDBAdaptor.DeclareGenerator@string
#define IDH_HTML_TCcDBAdaptor_DeclarePK_string             0x000000BB // TCcDBAdaptor.DeclarePK@string
#define IDH_HTML_TCcDBAdaptor_Destroy                      0x000000BC // TCcDBAdaptor.Destroy
#define IDH_HTML_TCcDBAdaptor_DropGenerator_string         0x000000BD // TCcDBAdaptor.DropGenerator@string
#define IDH_HTML_TCcDBAdaptor_DropProcedures               0x000000BE // TCcDBAdaptor.DropProcedures
#define IDH_HTML_TCcDBAdaptor_ExecutedReplicationQuery_String_String_TStringList 0x000000BF // TCcDBAdaptor.ExecutedReplicationQuery@String@String@TStringList
#define IDH_HTML_TCcDBAdaptor_ExecutingReplicationQuery_String_String_TStringList 0x000000C0 // TCcDBAdaptor.ExecutingReplicationQuery@String@String@TStringList
#define IDH_HTML_TCcDBAdaptor_ExecutingReplicationQuerySQL_String_String_TCcQuery 0x000000C1 // TCcDBAdaptor.ExecutingReplicationQuerySQL@String@String@TCcQuery
#define IDH_HTML_TCcDBAdaptor_FieldExists_string_string    0x000000C2 // TCcDBAdaptor.FieldExists@string@string
#define IDH_HTML_TCcDBAdaptor_GenDeclared_string           0x000000C3 // TCcDBAdaptor.GenDeclared@string
#define IDH_HTML_TCcDBAdaptor_GenerateTriggers_TCcQuery_TCcQuery_Boolean_Boolean 0x000000C4 // TCcDBAdaptor.GenerateTriggers@TCcQuery@TCcQuery@Boolean@Boolean
#define IDH_HTML_TCcDBAdaptor_GetAdaptorName               0x000000C5 // TCcDBAdaptor.GetAdaptorName
#define IDH_HTML_TCcDBAdaptor_GetGenerator_string_Integer  0x000000C6 // TCcDBAdaptor.GetGenerator@string@Integer
#define IDH_HTML_TCcDBAdaptor_GetInsertOrUpdateSQL_TStringList_TCcDBAdaptor_TStringList 0x000000C7 // TCcDBAdaptor.GetInsertOrUpdateSQL@TStringList@TCcDBAdaptor@TStringList
#define IDH_HTML_TCcDBAdaptor_GetProcGenerator_string_TDataSet_string_TStringList 0x000000C8 // TCcDBAdaptor.GetProcGenerator@string@TDataSet@string@TStringList
#define IDH_HTML_TCcDBAdaptor_GetProcParams_string_TDataSet_Boolean 0x000000C9 // TCcDBAdaptor.GetProcParams@string@TDataSet@Boolean
#define IDH_HTML_TCcDBAdaptor_GrantRightsToTable_string    0x000000CA // TCcDBAdaptor.GrantRightsToTable@string
#define IDH_HTML_TCcDBAdaptor_MetaQuote_string             0x000000CB // TCcDBAdaptor.MetaQuote@string
#define IDH_HTML_TCcDBAdaptor_MetaQuote_string_TCcDBAdaptor 0x000000CC // TCcDBAdaptor.MetaQuote@string@TCcDBAdaptor
#define IDH_HTML_TCcDBAdaptor_ProcedureExists_string       0x000000CD // TCcDBAdaptor.ProcedureExists@string
#define IDH_HTML_TCcDBAdaptor_RemoveCustomMetadata         0x000000CE // TCcDBAdaptor.RemoveCustomMetadata
#define IDH_HTML_TCcDBAdaptor_RemoveExtraCustomMetadata    0x000000CF // TCcDBAdaptor.RemoveExtraCustomMetadata
#define IDH_HTML_TCcDBAdaptor_RemoveTriggers_TCcQuery      0x000000D0 // TCcDBAdaptor.RemoveTriggers@TCcQuery
#define IDH_HTML_TCcDBAdaptor_SQLFormatValue_Variant_TFieldType 0x000000D1 // TCcDBAdaptor.SQLFormatValue@Variant@TFieldType
#define IDH_HTML_TCcDBAdaptor_SupportsGenerators           0x000000D2 // TCcDBAdaptor.SupportsGenerators
#define IDH_HTML_TCcDBAdaptor_SupportsInsertOrUpdate       0x000000D3 // TCcDBAdaptor.SupportsInsertOrUpdate
#define IDH_HTML_TCcDBAdaptor_TableExists_string           0x000000D4 // TCcDBAdaptor.TableExists@string
#define IDH_HTML_TCcDBAdaptor_TriggerExists_string         0x000000D5 // TCcDBAdaptor.TriggerExists@string
#define IDH_HTML_TCcDBAdaptor_UnQuotedIdentifier_string    0x000000D6 // TCcDBAdaptor.UnQuotedIdentifier@string
#define IDH_HTML_TCcDBAdaptorsEditor                       0x000000D7 // TCcDBAdaptorsEditor
#define IDH_HTML_TCcDBAdaptorsEditor_GetAttributes         0x000000D8 // TCcDBAdaptorsEditor.GetAttributes
#define IDH_HTML_TCcDBAdaptorsEditor_GetValues_TGetStrProc 0x000000D9 // TCcDBAdaptorsEditor.GetValues@TGetStrProc
#define IDH_HTML_TCcDBAdaptorVersionsEditor                0x000000DA // TCcDBAdaptorVersionsEditor
#define IDH_HTML_TCcDBAdaptorVersionsEditor_GetAttributes  0x000000DB // TCcDBAdaptorVersionsEditor.GetAttributes
#define IDH_HTML_TCcDBAdaptorVersionsEditor_GetValues_TGetStrProc 0x000000DC // TCcDBAdaptorVersionsEditor.GetValues@TGetStrProc
#define IDH_HTML_TCcDBAdaptorVersionsEditor_SetValue_string 0x000000DD // TCcDBAdaptorVersionsEditor.SetValue@string
#define IDH_HTML_TCcField                                  0x000000DE // TCcField
#define IDH_HTML_TCcField_AsCurrency                       0x000000DF // TCcField.AsCurrency
#define IDH_HTML_TCcField_AsDateTime                       0x000000E0 // TCcField.AsDateTime
#define IDH_HTML_TCcField_AsFloat                          0x000000E1 // TCcField.AsFloat
#define IDH_HTML_TCcField_AsInteger                        0x000000E2 // TCcField.AsInteger
#define IDH_HTML_TCcField_AsString                         0x000000E3 // TCcField.AsString
#define IDH_HTML_TCcField_DataType                         0x000000E4 // TCcField.DataType
#define IDH_HTML_TCcField_FieldName                        0x000000E5 // TCcField.FieldName
#define IDH_HTML_TCcField_index                            0x000000E6 // TCcField.index
#define IDH_HTML_TCcField_IsNull                           0x000000E7 // TCcField.IsNull
#define IDH_HTML_TCcField_IsParam                          0x000000E8 // TCcField.IsParam
#define IDH_HTML_TCcField_Size                             0x000000E9 // TCcField.Size
#define IDH_HTML_TCcField_Value                            0x000000EA // TCcField.Value
#define IDH_HTML_TCcField_Clear                            0x000000EB // TCcField.Clear
#define IDH_HTML_TCcField_Create_TCcQuery_string_TFieldType_Integer_Boolean 0x000000EC // TCcField.Create@TCcQuery@string@TFieldType@Integer@Boolean
#define IDH_HTML_TCcField_SetValueAsType_Variant_TFieldType 0x000000ED // TCcField.SetValueAsType@Variant@TFieldType
#define IDH_HTML_TCcFieldInfo                              0x000000EE // TCcFieldInfo
#define IDH_HTML_TCcFieldInfo_DataType                     0x000000EF // TCcFieldInfo.DataType
#define IDH_HTML_TCcFieldInfo_FieldName                    0x000000F0 // TCcFieldInfo.FieldName
#define IDH_HTML_TCcFieldInfo_IsNull                       0x000000F1 // TCcFieldInfo.IsNull
#define IDH_HTML_TCcFieldInfo_Size                         0x000000F2 // TCcFieldInfo.Size
#define IDH_HTML_TCcFieldInfo_Value                        0x000000F3 // TCcFieldInfo.Value
#define IDH_HTML_TCcFieldList                              0x000000F4 // TCcFieldList
#define IDH_HTML_TCcFieldList_Count                        0x000000F5 // TCcFieldList.Count
#define IDH_HTML_TCcFieldList_FieldInfo                    0x000000F6 // TCcFieldList.FieldInfo
#define IDH_HTML_TCcFieldList_FieldInfoByName              0x000000F7 // TCcFieldList.FieldInfoByName
#define IDH_HTML_TCcFieldList_Add_TCcFieldInfo             0x000000F8 // TCcFieldList.Add@TCcFieldInfo
#define IDH_HTML_TCcFieldList_Clear                        0x000000F9 // TCcFieldList.Clear
#define IDH_HTML_TCcFieldList_Create                       0x000000FA // TCcFieldList.Create
#define IDH_HTML_TCcFieldList_Destroy                      0x000000FB // TCcFieldList.Destroy
#define IDH_HTML_TCcInterbaseAdaptor                       0x000000FC // TCcInterbaseAdaptor
#define IDH_HTML_TCcInterbaseAdaptor_BranchVersion         0x000000FD // TCcInterbaseAdaptor.BranchVersion
#define IDH_HTML_TCcInterbaseAdaptor_DBBranch              0x000000FE // TCcInterbaseAdaptor.DBBranch
#define IDH_HTML_TCcInterbaseAdaptor_SQLDialect            0x000000FF // TCcInterbaseAdaptor.SQLDialect
#define IDH_HTML_TCcInterbaseAdaptor_CheckCustomMetadata   0x00000100 // TCcInterbaseAdaptor.CheckCustomMetadata
#define IDH_HTML_TCcInterbaseAdaptor_CheckExtraCustomMetadata 0x00000101 // TCcInterbaseAdaptor.CheckExtraCustomMetadata
#define IDH_HTML_TCcInterbaseAdaptor_ConvertValue_Variant_TFieldType 0x00000102 // TCcInterbaseAdaptor.ConvertValue@Variant@TFieldType
#define IDH_HTML_TCcInterbaseAdaptor_Create_TCcConnection  0x00000103 // TCcInterbaseAdaptor.Create@TCcConnection
#define IDH_HTML_TCcInterbaseAdaptor_CreateProcedures      0x00000104 // TCcInterbaseAdaptor.CreateProcedures
#define IDH_HTML_TCcInterbaseAdaptor_DeclareField_String_TFieldType_Integer_Boolean_Boolean_Boolean 0x00000105 // TCcInterbaseAdaptor.DeclareField@String@TFieldType@Integer@Boolean@Boolean@Boolean
#define IDH_HTML_TCcInterbaseAdaptor_DeclareGenerator_String 0x00000106 // TCcInterbaseAdaptor.DeclareGenerator@String
#define IDH_HTML_TCcInterbaseAdaptor_DeclarePK_String      0x00000107 // TCcInterbaseAdaptor.DeclarePK@String
#define IDH_HTML_TCcInterbaseAdaptor_Destroy               0x00000108 // TCcInterbaseAdaptor.Destroy
#define IDH_HTML_TCcInterbaseAdaptor_DropProcedures        0x00000109 // TCcInterbaseAdaptor.DropProcedures
#define IDH_HTML_TCcInterbaseAdaptor_GenDeclared_String    0x0000010A // TCcInterbaseAdaptor.GenDeclared@String
#define IDH_HTML_TCcInterbaseAdaptor_GenerateTriggers_TCcQuery_TCcQuery_Boolean_Boolean 0x0000010B // TCcInterbaseAdaptor.GenerateTriggers@TCcQuery@TCcQuery@Boolean@Boolean
#define IDH_HTML_TCcInterbaseAdaptor_GetAdaptorName        0x0000010C // TCcInterbaseAdaptor.GetAdaptorName
#define IDH_HTML_TCcInterbaseAdaptor_GetGenerator_String_Integer 0x0000010D // TCcInterbaseAdaptor.GetGenerator@String@Integer
#define IDH_HTML_TCcInterbaseAdaptor_GetGeneratorValue_String_Integer 0x0000010E // TCcInterbaseAdaptor.GetGeneratorValue@String@Integer
#define IDH_HTML_TCcInterbaseAdaptor_GetProcParams_String_TDataSet_Boolean 0x0000010F // TCcInterbaseAdaptor.GetProcParams@String@TDataSet@Boolean
#define IDH_HTML_TCcInterbaseAdaptor_RemoveCustomMetadata  0x00000110 // TCcInterbaseAdaptor.RemoveCustomMetadata
#define IDH_HTML_TCcInterbaseAdaptor_RemoveExtraCustomMetadata 0x00000111 // TCcInterbaseAdaptor.RemoveExtraCustomMetadata
#define IDH_HTML_TCcInterbaseAdaptor_RemoveTriggers_TCcQuery 0x00000112 // TCcInterbaseAdaptor.RemoveTriggers@TCcQuery
#define IDH_HTML_TCcInterbaseAdaptor_SQLFormatValue_Variant_TFieldType 0x00000113 // TCcInterbaseAdaptor.SQLFormatValue@Variant@TFieldType
#define IDH_HTML_TCcInterbaseAdaptor_SupportsGenerators    0x00000114 // TCcInterbaseAdaptor.SupportsGenerators
#define IDH_HTML_TCcInterbaseConnection                    0x00000115 // TCcInterbaseConnection
#define IDH_HTML_TCcInterbaseConnection_CharSet            0x00000116 // TCcInterbaseConnection.CharSet
#define IDH_HTML_TCcInterbaseConnection_DBName             0x00000117 // TCcInterbaseConnection.DBName
#define IDH_HTML_TCcInterbaseConnection_DBType             0x00000118 // TCcInterbaseConnection.DBType
#define IDH_HTML_TCcInterbaseConnection_DBVersion          0x00000119 // TCcInterbaseConnection.DBVersion
#define IDH_HTML_TCcInterbaseConnection_RoleName           0x0000011A // TCcInterbaseConnection.RoleName
#define IDH_HTML_TCcInterbaseConnection_SQLDialect         0x0000011B // TCcInterbaseConnection.SQLDialect
#define IDH_HTML_TCcInterbaseConnection_TRParams           0x0000011C // TCcInterbaseConnection.TRParams
#define IDH_HTML_TCcInterbaseConnection_UserLogin          0x0000011D // TCcInterbaseConnection.UserLogin
#define IDH_HTML_TCcInterbaseConnection_UserPassword       0x0000011E // TCcInterbaseConnection.UserPassword
#define IDH_HTML_TCcInterbaseConnection_Assign_TPersistent 0x0000011F // TCcInterbaseConnection.Assign@TPersistent
#define IDH_HTML_TCcInterbaseConnection_Create_TComponent  0x00000120 // TCcInterbaseConnection.Create@TComponent
#define IDH_HTML_TCcInterbaseConnection_Destroy            0x00000121 // TCcInterbaseConnection.Destroy
#define IDH_HTML_TCcInternalMemoryData                     0x00000122 // TCcInternalMemoryData
#define IDH_HTML_TCcInternalMemoryData_Active              0x00000123 // TCcInternalMemoryData.Active
#define IDH_HTML_TCcInternalMemoryData_AfterCancel         0x00000124 // TCcInternalMemoryData.AfterCancel
#define IDH_HTML_TCcInternalMemoryData_AfterClose          0x00000125 // TCcInternalMemoryData.AfterClose
#define IDH_HTML_TCcInternalMemoryData_AfterDelete         0x00000126 // TCcInternalMemoryData.AfterDelete
#define IDH_HTML_TCcInternalMemoryData_AfterEdit           0x00000127 // TCcInternalMemoryData.AfterEdit
#define IDH_HTML_TCcInternalMemoryData_AfterInsert         0x00000128 // TCcInternalMemoryData.AfterInsert
#define IDH_HTML_TCcInternalMemoryData_AfterOpen           0x00000129 // TCcInternalMemoryData.AfterOpen
#define IDH_HTML_TCcInternalMemoryData_AfterPost           0x0000012A // TCcInternalMemoryData.AfterPost
#define IDH_HTML_TCcInternalMemoryData_AfterScroll         0x0000012B // TCcInternalMemoryData.AfterScroll
#define IDH_HTML_TCcInternalMemoryData_BeforeCancel        0x0000012C // TCcInternalMemoryData.BeforeCancel
#define IDH_HTML_TCcInternalMemoryData_BeforeClose         0x0000012D // TCcInternalMemoryData.BeforeClose
#define IDH_HTML_TCcInternalMemoryData_BeforeDelete        0x0000012E // TCcInternalMemoryData.BeforeDelete
#define IDH_HTML_TCcInternalMemoryData_BeforeEdit          0x0000012F // TCcInternalMemoryData.BeforeEdit
#define IDH_HTML_TCcInternalMemoryData_BeforeInsert        0x00000130 // TCcInternalMemoryData.BeforeInsert
#define IDH_HTML_TCcInternalMemoryData_BeforeOpen          0x00000131 // TCcInternalMemoryData.BeforeOpen
#define IDH_HTML_TCcInternalMemoryData_BeforePost          0x00000132 // TCcInternalMemoryData.BeforePost
#define IDH_HTML_TCcInternalMemoryData_BeforeScroll        0x00000133 // TCcInternalMemoryData.BeforeScroll
#define IDH_HTML_TCcInternalMemoryData_Capacity            0x00000134 // TCcInternalMemoryData.Capacity
#define IDH_HTML_TCcInternalMemoryData_OnCalcFields        0x00000135 // TCcInternalMemoryData.OnCalcFields
#define IDH_HTML_TCcInternalMemoryData_OnDeleteError       0x00000136 // TCcInternalMemoryData.OnDeleteError
#define IDH_HTML_TCcInternalMemoryData_OnEditError         0x00000137 // TCcInternalMemoryData.OnEditError
#define IDH_HTML_TCcInternalMemoryData_OnFilterRecord      0x00000138 // TCcInternalMemoryData.OnFilterRecord
#define IDH_HTML_TCcInternalMemoryData_OnNewRecord         0x00000139 // TCcInternalMemoryData.OnNewRecord
#define IDH_HTML_TCcInternalMemoryData_OnPostError         0x0000013A // TCcInternalMemoryData.OnPostError
#define IDH_HTML_TCcInternalMemoryData_BookmarkValid_TBookmark 0x0000013B // TCcInternalMemoryData.BookmarkValid@TBookmark
#define IDH_HTML_TCcInternalMemoryData_CompareBookmarks_TBookmark_TBookmark 0x0000013C // TCcInternalMemoryData.CompareBookmarks@TBookmark@TBookmark
#define IDH_HTML_TCcInternalMemoryData_Create_TComponent   0x0000013D // TCcInternalMemoryData.Create@TComponent
#define IDH_HTML_TCcInternalMemoryData_CreateBlobStream_TField_TBlobStreamMode 0x0000013E // TCcInternalMemoryData.CreateBlobStream@TField@TBlobStreamMode
#define IDH_HTML_TCcInternalMemoryData_Destroy             0x0000013F // TCcInternalMemoryData.Destroy
#define IDH_HTML_TCcInternalMemoryData_EmptyTable          0x00000140 // TCcInternalMemoryData.EmptyTable
#define IDH_HTML_TCcInternalMemoryData_GetCurrentRecord_PCcMemBuffer 0x00000141 // TCcInternalMemoryData.GetCurrentRecord@PCcMemBuffer
#define IDH_HTML_TCcInternalMemoryData_GetFieldData_TField_Pointer 0x00000142 // TCcInternalMemoryData.GetFieldData@TField@Pointer
#define IDH_HTML_TCcInternalMemoryData_GetFieldData_TField_TValueBuffer 0x00000143 // TCcInternalMemoryData.GetFieldData@TField@TValueBuffer
#define IDH_HTML_TCcInternalMemoryData_IsSequenced         0x00000144 // TCcInternalMemoryData.IsSequenced
#define IDH_HTML_TCcInternalMemoryData_Locate_string_Variant_TLocateOptions 0x00000145 // TCcInternalMemoryData.Locate@string@Variant@TLocateOptions
#define IDH_HTML_TCcInternalMemoryData_SaveToDataSet_TDataSet_Integer 0x00000146 // TCcInternalMemoryData.SaveToDataSet@TDataSet@Integer
#define IDH_HTML_TCcInternalMemoryData_SortOnFields_string_Boolean_Boolean 0x00000147 // TCcInternalMemoryData.SortOnFields@string@Boolean@Boolean
#define IDH_HTML_TCcKey                                    0x00000148 // TCcKey
#define IDH_HTML_TCcKey_DataType                           0x00000149 // TCcKey.DataType
#define IDH_HTML_TCcKey_GenericSyncStatement               0x0000014A // TCcKey.GenericSyncStatement
#define IDH_HTML_TCcKey_KeyName                            0x0000014B // TCcKey.KeyName
#define IDH_HTML_TCcKey_KeyValue                           0x0000014C // TCcKey.KeyValue
#define IDH_HTML_TCcKey_OriginalKeyValue                   0x0000014D // TCcKey.OriginalKeyValue
#define IDH_HTML_TCcKey_PrimaryKey                         0x0000014E // TCcKey.PrimaryKey
#define IDH_HTML_TCcKey_SyncStatement                      0x0000014F // TCcKey.SyncStatement
#define IDH_HTML_TCcKeyRing                                0x00000150 // TCcKeyRing
#define IDH_HTML_TCcKeyRing_Count                          0x00000151 // TCcKeyRing.Count
#define IDH_HTML_TCcKeyRing_FailIfNoPK                     0x00000152 // TCcKeyRing.FailIfNoPK
#define IDH_HTML_TCcKeyRing_GenericPrimaryKeySync          0x00000153 // TCcKeyRing.GenericPrimaryKeySync
#define IDH_HTML_TCcKeyRing_GenericUniqueKeySync           0x00000154 // TCcKeyRing.GenericUniqueKeySync
#define IDH_HTML_TCcKeyRing_Keys                           0x00000155 // TCcKeyRing.Keys
#define IDH_HTML_TCcKeyRing_PrimaryKeySync                 0x00000156 // TCcKeyRing.PrimaryKeySync
#define IDH_HTML_TCcKeyRing_PrimaryKeyValues               0x00000157 // TCcKeyRing.PrimaryKeyValues
#define IDH_HTML_TCcKeyRing_TableKeys                      0x00000158 // TCcKeyRing.TableKeys
#define IDH_HTML_TCcKeyRing_TableName                      0x00000159 // TCcKeyRing.TableName
#define IDH_HTML_TCcKeyRing_UniqueKeyNames                 0x0000015A // TCcKeyRing.UniqueKeyNames
#define IDH_HTML_TCcKeyRing_UniqueKeySync                  0x0000015B // TCcKeyRing.UniqueKeySync
#define IDH_HTML_TCcKeyRing_Clear                          0x0000015C // TCcKeyRing.Clear
#define IDH_HTML_TCcKeyRing_ClearTableKeys                 0x0000015D // TCcKeyRing.ClearTableKeys
#define IDH_HTML_TCcKeyRing_Create_TCcConnection           0x0000015E // TCcKeyRing.Create@TCcConnection
#define IDH_HTML_TCcKeyRing_Destroy                        0x0000015F // TCcKeyRing.Destroy
#define IDH_HTML_TCcKeyRing_FindKey_String                 0x00000160 // TCcKeyRing.FindKey@String
#define IDH_HTML_TCcKeyRing_KeyExists_String               0x00000161 // TCcKeyRing.KeyExists@String
#define IDH_HTML_TCcKeyRing_LoadFromDataSet_TDataSet_String_String_String 0x00000162 // TCcKeyRing.LoadFromDataSet@TDataSet@String@String@String
#define IDH_HTML_TCcKeyRing_LoadKeys_String_String_String_String_String_String_String_TCcKeyOrigin 0x00000163 // TCcKeyRing.LoadKeys@String@String@String@String@String@String@String@TCcKeyOrigin
#define IDH_HTML_TCcKeyRing_LoadKeysFromDataSet_String_TCcMemoryTable_String_String 0x00000164 // TCcKeyRing.LoadKeysFromDataSet@String@TCcMemoryTable@String@String
#define IDH_HTML_TCcKeyRing_LoadKeysFromDataSet_String_TCcQuery_String_String 0x00000165 // TCcKeyRing.LoadKeysFromDataSet@String@TCcQuery@String@String
#define IDH_HTML_TCcKeyRing_SaveKeys                       0x00000166 // TCcKeyRing.SaveKeys
#define IDH_HTML_TCcKeyRing_SaveToDataSet_TDataSet_String_String_Boolean 0x00000167 // TCcKeyRing.SaveToDataSet@TDataSet@String@String@Boolean
#define IDH_HTML_TCcLog                                    0x00000168 // TCcLog
#define IDH_HTML_TCcLog_Create_TComponent                  0x00000169 // TCcLog.Create@TComponent
#define IDH_HTML_TCcLog_Destroy                            0x0000016A // TCcLog.Destroy
#define IDH_HTML_TCcLog_FBN_string                         0x0000016B // TCcLog.FBN@string
#define IDH_HTML_TCcLog_FieldByName_string                 0x0000016C // TCcLog.FieldByName@string
#define IDH_HTML_TCcLog_FieldExists_string                 0x0000016D // TCcLog.FieldExists@string
#define IDH_HTML_TCcLog_ListChangedFields_TCcConnection_TStringList_String_String_String 0x0000016E // TCcLog.ListChangedFields@TCcConnection@TStringList@String@String@String
#define IDH_HTML_TCcLog_Next                               0x0000016F // TCcLog.Next
#define IDH_HTML_TCcLogConfigListener                      0x00000170 // TCcLogConfigListener
#define IDH_HTML_TCcLogFile                                0x00000171 // TCcLogFile
#define IDH_HTML_TCcLogFile_Create_TComponent              0x00000172 // TCcLogFile.Create@TComponent
#define IDH_HTML_TCcLogFileList                            0x00000173 // TCcLogFileList
#define IDH_HTML_TCcLogFileList_Active                     0x00000174 // TCcLogFileList.Active
#define IDH_HTML_TCcLogFileList_ConfigName                 0x00000175 // TCcLogFileList.ConfigName
#define IDH_HTML_TCcLogFileList_ConfigNames                0x00000176 // TCcLogFileList.ConfigNames
#define IDH_HTML_TCcLogFileList_ConfigStorage              0x00000177 // TCcLogFileList.ConfigStorage
#define IDH_HTML_TCcLogFileList_Logs                       0x00000178 // TCcLogFileList.Logs
#define IDH_HTML_TCcLogFileList_OnLogLine                  0x00000179 // TCcLogFileList.OnLogLine
#define IDH_HTML_TCcLogFileList_Clear                      0x0000017A // TCcLogFileList.Clear
#define IDH_HTML_TCcLogFileList_Create_TComponent          0x0000017B // TCcLogFileList.Create@TComponent
#define IDH_HTML_TCcLogFileList_Destroy                    0x0000017C // TCcLogFileList.Destroy
#define IDH_HTML_TCcMacro                                  0x0000017D // TCcMacro
#define IDH_HTML_TCcMacro_name                             0x0000017E // TCcMacro.name
#define IDH_HTML_TCcMacro_Value                            0x0000017F // TCcMacro.Value
#define IDH_HTML_TCcMemoField                              0x00000180 // TCcMemoField
#define IDH_HTML_TCcMemoField_GetAsVariant                 0x00000181 // TCcMemoField.GetAsVariant
#define IDH_HTML_TCcMemoryData                             0x00000182 // TCcMemoryData
#define IDH_HTML_TCcMemoryData_AddField_string_TFieldType_Integer 0x00000183 // TCcMemoryData.AddField@string@TFieldType@Integer
#define IDH_HTML_TCcMemoryData_SortRows_string_Boolean     0x00000184 // TCcMemoryData.SortRows@string@Boolean
#define IDH_HTML_TCcMemoryField                            0x00000185 // TCcMemoryField
#define IDH_HTML_TCcMemoryField_AsString                   0x00000186 // TCcMemoryField.AsString
#define IDH_HTML_TCcMemoryField_DataType                   0x00000187 // TCcMemoryField.DataType
#define IDH_HTML_TCcMemoryField_FieldName                  0x00000188 // TCcMemoryField.FieldName
#define IDH_HTML_TCcMemoryField_index                      0x00000189 // TCcMemoryField.index
#define IDH_HTML_TCcMemoryField_IsNull                     0x0000018A // TCcMemoryField.IsNull
#define IDH_HTML_TCcMemoryField_Size                       0x0000018B // TCcMemoryField.Size
#define IDH_HTML_TCcMemoryField_Value                      0x0000018C // TCcMemoryField.Value
#define IDH_HTML_TCcMemoryField_Visible                    0x0000018D // TCcMemoryField.Visible
#define IDH_HTML_TCcMemoryField_Clear                      0x0000018E // TCcMemoryField.Clear
#define IDH_HTML_TCcMemoryField_Create_TCcMemoryFields     0x0000018F // TCcMemoryField.Create@TCcMemoryFields
#define IDH_HTML_TCcMemoryFields                           0x00000190 // TCcMemoryFields
#define IDH_HTML_TCcMemoryFields_Count                     0x00000191 // TCcMemoryFields.Count
#define IDH_HTML_TCcMemoryFields_FieldByIndex              0x00000192 // TCcMemoryFields.FieldByIndex
#define IDH_HTML_TCcMemoryFields_Add_String                0x00000193 // TCcMemoryFields.Add@String
#define IDH_HTML_TCcMemoryFields_Clear                     0x00000194 // TCcMemoryFields.Clear
#define IDH_HTML_TCcMemoryFields_Create_TCcMemoryTable     0x00000195 // TCcMemoryFields.Create@TCcMemoryTable
#define IDH_HTML_TCcMemoryFields_Delete_Integer            0x00000196 // TCcMemoryFields.Delete@Integer
#define IDH_HTML_TCcMemoryFields_Destroy                   0x00000197 // TCcMemoryFields.Destroy
#define IDH_HTML_TCcMemoryFields_FieldByName_string        0x00000198 // TCcMemoryFields.FieldByName@string
#define IDH_HTML_TCcMemoryFields_FindField_string          0x00000199 // TCcMemoryFields.FindField@string
#define IDH_HTML_TCcMemoryRow                              0x0000019A // TCcMemoryRow
#define IDH_HTML_TCcMemoryRow_Count                        0x0000019B // TCcMemoryRow.Count
#define IDH_HTML_TCcMemoryRow_Value                        0x0000019C // TCcMemoryRow.Value
#define IDH_HTML_TCcMemoryRow_CopyFrom_TCcMemoryRow        0x0000019D // TCcMemoryRow.CopyFrom@TCcMemoryRow
#define IDH_HTML_TCcMemoryRow_Create_TCcMemoryTable        0x0000019E // TCcMemoryRow.Create@TCcMemoryTable
#define IDH_HTML_TCcMemoryRow_Destroy                      0x0000019F // TCcMemoryRow.Destroy
#define IDH_HTML_TCcMemoryTable                            0x000001A0 // TCcMemoryTable
#define IDH_HTML_TCcMemoryTable_Active                     0x000001A1 // TCcMemoryTable.Active
#define IDH_HTML_TCcMemoryTable_Bof                        0x000001A2 // TCcMemoryTable.Bof
#define IDH_HTML_TCcMemoryTable_CanCancelEdits             0x000001A3 // TCcMemoryTable.CanCancelEdits
#define IDH_HTML_TCcMemoryTable_Eof                        0x000001A4 // TCcMemoryTable.Eof
#define IDH_HTML_TCcMemoryTable_fields                     0x000001A5 // TCcMemoryTable.fields
#define IDH_HTML_TCcMemoryTable_RecNo                      0x000001A6 // TCcMemoryTable.RecNo
#define IDH_HTML_TCcMemoryTable_RecordCount                0x000001A7 // TCcMemoryTable.RecordCount
#define IDH_HTML_TCcMemoryTable_AddNewRecord               0x000001A8 // TCcMemoryTable.AddNewRecord
#define IDH_HTML_TCcMemoryTable_Append                     0x000001A9 // TCcMemoryTable.Append
#define IDH_HTML_TCcMemoryTable_CancelChanges              0x000001AA // TCcMemoryTable.CancelChanges
#define IDH_HTML_TCcMemoryTable_CheckActive                0x000001AB // TCcMemoryTable.CheckActive
#define IDH_HTML_TCcMemoryTable_CheckInactive              0x000001AC // TCcMemoryTable.CheckInactive
#define IDH_HTML_TCcMemoryTable_Clear                      0x000001AD // TCcMemoryTable.Clear
#define IDH_HTML_TCcMemoryTable_CopyStructure_TCcQuery     0x000001AE // TCcMemoryTable.CopyStructure@TCcQuery
#define IDH_HTML_TCcMemoryTable_Create_TComponent          0x000001AF // TCcMemoryTable.Create@TComponent
#define IDH_HTML_TCcMemoryTable_Delete                     0x000001B0 // TCcMemoryTable.Delete
#define IDH_HTML_TCcMemoryTable_Destroy                    0x000001B1 // TCcMemoryTable.Destroy
#define IDH_HTML_TCcMemoryTable_EditCurrentRecord          0x000001B2 // TCcMemoryTable.EditCurrentRecord
#define IDH_HTML_TCcMemoryTable_FieldByName_string         0x000001B3 // TCcMemoryTable.FieldByName@string
#define IDH_HTML_TCcMemoryTable_FindField_string           0x000001B4 // TCcMemoryTable.FindField@string
#define IDH_HTML_TCcMemoryTable_First                      0x000001B5 // TCcMemoryTable.First
#define IDH_HTML_TCcMemoryTable_Last                       0x000001B6 // TCcMemoryTable.Last
#define IDH_HTML_TCcMemoryTable_LoadFromDataSet_TCcQuery_Boolean_Boolean_Boolean 0x000001B7 // TCcMemoryTable.LoadFromDataSet@TCcQuery@Boolean@Boolean@Boolean
#define IDH_HTML_TCcMemoryTable_Next                       0x000001B8 // TCcMemoryTable.Next
#define IDH_HTML_TCcMemoryTable_PostChanges                0x000001B9 // TCcMemoryTable.PostChanges
#define IDH_HTML_TCcMemoryTable_Prior                      0x000001BA // TCcMemoryTable.Prior
#define IDH_HTML_TCcMySQLAdaptor                           0x000001BB // TCcMySQLAdaptor
#define IDH_HTML_TCcMySQLAdaptor_CheckCustomMetadata       0x000001BC // TCcMySQLAdaptor.CheckCustomMetadata
#define IDH_HTML_TCcMySQLAdaptor_ConvertValue_Variant_TFieldType 0x000001BD // TCcMySQLAdaptor.ConvertValue@Variant@TFieldType
#define IDH_HTML_TCcMySQLAdaptor_Create_TCcConnection      0x000001BE // TCcMySQLAdaptor.Create@TCcConnection
#define IDH_HTML_TCcMySQLAdaptor_CreateProcedures          0x000001BF // TCcMySQLAdaptor.CreateProcedures
#define IDH_HTML_TCcMySQLAdaptor_DeclareField_String_TFieldType_Integer_Boolean_Boolean_Boolean 0x000001C0 // TCcMySQLAdaptor.DeclareField@String@TFieldType@Integer@Boolean@Boolean@Boolean
#define IDH_HTML_TCcMySQLAdaptor_DeclareGenerator_String   0x000001C1 // TCcMySQLAdaptor.DeclareGenerator@String
#define IDH_HTML_TCcMySQLAdaptor_Destroy                   0x000001C2 // TCcMySQLAdaptor.Destroy
#define IDH_HTML_TCcMySQLAdaptor_DropProcedures            0x000001C3 // TCcMySQLAdaptor.DropProcedures
#define IDH_HTML_TCcMySQLAdaptor_GenDeclared_String        0x000001C4 // TCcMySQLAdaptor.GenDeclared@String
#define IDH_HTML_TCcMySQLAdaptor_GenerateTriggers_TCcQuery_TCcQuery_Boolean_Boolean 0x000001C5 // TCcMySQLAdaptor.GenerateTriggers@TCcQuery@TCcQuery@Boolean@Boolean
#define IDH_HTML_TCcMySQLAdaptor_GetAdaptorName            0x000001C6 // TCcMySQLAdaptor.GetAdaptorName
#define IDH_HTML_TCcMySQLAdaptor_GetGenerator_String_Integer 0x000001C7 // TCcMySQLAdaptor.GetGenerator@String@Integer
#define IDH_HTML_TCcMySQLAdaptor_GetProcParams_String_TDataSet_Boolean 0x000001C8 // TCcMySQLAdaptor.GetProcParams@String@TDataSet@Boolean
#define IDH_HTML_TCcMySQLAdaptor_GrantRightsToTable_String 0x000001C9 // TCcMySQLAdaptor.GrantRightsToTable@String
#define IDH_HTML_TCcMySQLAdaptor_RemoveCustomMetadata      0x000001CA // TCcMySQLAdaptor.RemoveCustomMetadata
#define IDH_HTML_TCcMySQLAdaptor_RemoveTriggers_TCcQuery   0x000001CB // TCcMySQLAdaptor.RemoveTriggers@TCcQuery
#define IDH_HTML_TCcMySQLAdaptor_SQLFormatValue_Variant_TFieldType 0x000001CC // TCcMySQLAdaptor.SQLFormatValue@Variant@TFieldType
#define IDH_HTML_TCcMySQLAdaptor_SupportsGenerators        0x000001CD // TCcMySQLAdaptor.SupportsGenerators
#define IDH_HTML_TCcNexusDBAdaptor                         0x000001CE // TCcNexusDBAdaptor
#define IDH_HTML_TCcNexusDBAdaptor_CheckCustomMetadata     0x000001CF // TCcNexusDBAdaptor.CheckCustomMetadata
#define IDH_HTML_TCcNexusDBAdaptor_ConvertValue_Variant_TFieldType 0x000001D0 // TCcNexusDBAdaptor.ConvertValue@Variant@TFieldType
#define IDH_HTML_TCcNexusDBAdaptor_Create_TCcConnection    0x000001D1 // TCcNexusDBAdaptor.Create@TCcConnection
#define IDH_HTML_TCcNexusDBAdaptor_DeclareField_string_TFieldType_Integer_Boolean_Boolean_Boolean 0x000001D2 // TCcNexusDBAdaptor.DeclareField@string@TFieldType@Integer@Boolean@Boolean@Boolean
#define IDH_HTML_TCcNexusDBAdaptor_DeclarePK_string        0x000001D3 // TCcNexusDBAdaptor.DeclarePK@string
#define IDH_HTML_TCcNexusDBAdaptor_Destroy                 0x000001D4 // TCcNexusDBAdaptor.Destroy
#define IDH_HTML_TCcNexusDBAdaptor_GenDeclared_string      0x000001D5 // TCcNexusDBAdaptor.GenDeclared@string
#define IDH_HTML_TCcNexusDBAdaptor_GenerateTriggers_TCcQuery_TCcQuery_Boolean_Boolean 0x000001D6 // TCcNexusDBAdaptor.GenerateTriggers@TCcQuery@TCcQuery@Boolean@Boolean
#define IDH_HTML_TCcNexusDBAdaptor_GetAdaptorName          0x000001D7 // TCcNexusDBAdaptor.GetAdaptorName
#define IDH_HTML_TCcNexusDBAdaptor_GrantRightsToTable_String 0x000001D8 // TCcNexusDBAdaptor.GrantRightsToTable@String
#define IDH_HTML_TCcNexusDBAdaptor_RemoveCustomMetadata    0x000001D9 // TCcNexusDBAdaptor.RemoveCustomMetadata
#define IDH_HTML_TCcNexusDBAdaptor_RemoveTriggers_TCcQuery 0x000001DA // TCcNexusDBAdaptor.RemoveTriggers@TCcQuery
#define IDH_HTML_TCcNexusDBAdaptor_SQLFormatValue_Variant_TFieldType 0x000001DB // TCcNexusDBAdaptor.SQLFormatValue@Variant@TFieldType
#define IDH_HTML_TCcNexusDBAdaptor_SupportsGenerators      0x000001DC // TCcNexusDBAdaptor.SupportsGenerators
#define IDH_HTML_TCcNode                                   0x000001DD // TCcNode
#define IDH_HTML_TCcNode_ConfigName                        0x000001DE // TCcNode.ConfigName
#define IDH_HTML_TCcNode_Connection                        0x000001DF // TCcNode.Connection
#define IDH_HTML_TCcNode_CurrentTableName                  0x000001E0 // TCcNode.CurrentTableName
#define IDH_HTML_TCcNode_Name                              0x000001E1 // TCcNode.Name
#define IDH_HTML_TCcNode_Password                          0x000001E2 // TCcNode.Password
#define IDH_HTML_TCcNode_Create_TCcReplicator              0x000001E3 // TCcNode.Create@TCcReplicator
#define IDH_HTML_TCcNode_FindConfigName_TCcNode            0x000001E4 // TCcNode.FindConfigName@TCcNode
#define IDH_HTML_TCcNodes                                  0x000001E5 // TCcNodes
#define IDH_HTML_TCcNodes_LocalNode                        0x000001E6 // TCcNodes.LocalNode
#define IDH_HTML_TCcNodes_RemoteNode                       0x000001E7 // TCcNodes.RemoteNode
#define IDH_HTML_TCcNodes_Create_TCcReplicator             0x000001E8 // TCcNodes.Create@TCcReplicator
#define IDH_HTML_TCcNodes_Destroy                          0x000001E9 // TCcNodes.Destroy
#define IDH_HTML_TCcPostgresAdaptor                        0x000001EA // TCcPostgresAdaptor
#define IDH_HTML_TCcPostgresAdaptor_BranchVersion          0x000001EB // TCcPostgresAdaptor.BranchVersion
#define IDH_HTML_TCcPostgresAdaptor_CheckCustomMetadata    0x000001EC // TCcPostgresAdaptor.CheckCustomMetadata
#define IDH_HTML_TCcPostgresAdaptor_CheckExtraCustomMetadata 0x000001ED // TCcPostgresAdaptor.CheckExtraCustomMetadata
#define IDH_HTML_TCcPostgresAdaptor_ConvertValue_Variant_TFieldType 0x000001EE // TCcPostgresAdaptor.ConvertValue@Variant@TFieldType
#define IDH_HTML_TCcPostgresAdaptor_Create_TCcConnection   0x000001EF // TCcPostgresAdaptor.Create@TCcConnection
#define IDH_HTML_TCcPostgresAdaptor_CreateProcedures       0x000001F0 // TCcPostgresAdaptor.CreateProcedures
#define IDH_HTML_TCcPostgresAdaptor_DeclareField_String_TFieldType_Integer_Boolean_Boolean_Boolean 0x000001F1 // TCcPostgresAdaptor.DeclareField@String@TFieldType@Integer@Boolean@Boolean@Boolean
#define IDH_HTML_TCcPostgresAdaptor_DeclareGenerator_String 0x000001F2 // TCcPostgresAdaptor.DeclareGenerator@String
#define IDH_HTML_TCcPostgresAdaptor_DeclarePK_String       0x000001F3 // TCcPostgresAdaptor.DeclarePK@String
#define IDH_HTML_TCcPostgresAdaptor_Destroy                0x000001F4 // TCcPostgresAdaptor.Destroy
#define IDH_HTML_TCcPostgresAdaptor_DropProcedures         0x000001F5 // TCcPostgresAdaptor.DropProcedures
#define IDH_HTML_TCcPostgresAdaptor_GenDeclared_String     0x000001F6 // TCcPostgresAdaptor.GenDeclared@String
#define IDH_HTML_TCcPostgresAdaptor_GenerateTriggers_TCcQuery_TCcQuery_Boolean_Boolean 0x000001F7 // TCcPostgresAdaptor.GenerateTriggers@TCcQuery@TCcQuery@Boolean@Boolean
#define IDH_HTML_TCcPostgresAdaptor_GetAdaptorName         0x000001F8 // TCcPostgresAdaptor.GetAdaptorName
#define IDH_HTML_TCcPostgresAdaptor_GetGenerator_String_Integer 0x000001F9 // TCcPostgresAdaptor.GetGenerator@String@Integer
#define IDH_HTML_TCcPostgresAdaptor_GetGeneratorValue_String_Integer 0x000001FA // TCcPostgresAdaptor.GetGeneratorValue@String@Integer
#define IDH_HTML_TCcPostgresAdaptor_RemoveCustomMetadata   0x000001FB // TCcPostgresAdaptor.RemoveCustomMetadata
#define IDH_HTML_TCcPostgresAdaptor_RemoveExtraCustomMetadata 0x000001FC // TCcPostgresAdaptor.RemoveExtraCustomMetadata
#define IDH_HTML_TCcPostgresAdaptor_RemoveTriggers_TCcQuery 0x000001FD // TCcPostgresAdaptor.RemoveTriggers@TCcQuery
#define IDH_HTML_TCcPostgresAdaptor_SQLFormatValue_Variant_TFieldType 0x000001FE // TCcPostgresAdaptor.SQLFormatValue@Variant@TFieldType
#define IDH_HTML_TCcPostgresAdaptor_SupportsGenerators     0x000001FF // TCcPostgresAdaptor.SupportsGenerators
#define IDH_HTML_TCcPostgresAdaptor_UnQuotedIdentifier_String 0x00000200 // TCcPostgresAdaptor.UnQuotedIdentifier@String
#define IDH_HTML_TCcProcParams                             0x00000201 // TCcProcParams
#define IDH_HTML_TCcProcParams_Create_TComponent           0x00000202 // TCcProcParams.Create@TComponent
#define IDH_HTML_TCcQuery                                  0x00000203 // TCcQuery
#define IDH_HTML_TCcQuery_Active                           0x00000204 // TCcQuery.Active
#define IDH_HTML_TCcQuery_Connection                       0x00000205 // TCcQuery.Connection
#define IDH_HTML_TCcQuery_Eof                              0x00000206 // TCcQuery.Eof
#define IDH_HTML_TCcQuery_Field                            0x00000207 // TCcQuery.Field
#define IDH_HTML_TCcQuery_FieldByIndex                     0x00000208 // TCcQuery.FieldByIndex
#define IDH_HTML_TCcQuery_FieldCount                       0x00000209 // TCcQuery.FieldCount
#define IDH_HTML_TCcQuery_Macro                            0x0000020A // TCcQuery.Macro
#define IDH_HTML_TCcQuery_MacroCount                       0x0000020B // TCcQuery.MacroCount
#define IDH_HTML_TCcQuery_Param                            0x0000020C // TCcQuery.Param
#define IDH_HTML_TCcQuery_ParamByIndex                     0x0000020D // TCcQuery.ParamByIndex
#define IDH_HTML_TCcQuery_ParamCheck                       0x0000020E // TCcQuery.ParamCheck
#define IDH_HTML_TCcQuery_ParamCount                       0x0000020F // TCcQuery.ParamCount
#define IDH_HTML_TCcQuery_Prepared                         0x00000210 // TCcQuery.Prepared
#define IDH_HTML_TCcQuery_Properties                       0x00000211 // TCcQuery.Properties
#define IDH_HTML_TCcQuery_QueryID                          0x00000212 // TCcQuery.QueryID
#define IDH_HTML_TCcQuery_RealSQL                          0x00000213 // TCcQuery.RealSQL
#define IDH_HTML_TCcQuery_RecordCount                      0x00000214 // TCcQuery.RecordCount
#define IDH_HTML_TCcQuery_RowsAffected                     0x00000215 // TCcQuery.RowsAffected
#define IDH_HTML_TCcQuery_SelectStatement                  0x00000216 // TCcQuery.SelectStatement
#define IDH_HTML_TCcQuery_SQL                              0x00000217 // TCcQuery.SQL
#define IDH_HTML_TCcQuery_CheckInactive                    0x00000218 // TCcQuery.CheckInactive
#define IDH_HTML_TCcQuery_Close                            0x00000219 // TCcQuery.Close
#define IDH_HTML_TCcQuery_Create_TCcConnection_string_Boolean 0x0000021A // TCcQuery.Create@TCcConnection@string@Boolean
#define IDH_HTML_TCcQuery_Create_TComponent                0x0000021B // TCcQuery.Create@TComponent
#define IDH_HTML_TCcQuery_Destroy                          0x0000021C // TCcQuery.Destroy
#define IDH_HTML_TCcQuery_Exec                             0x0000021D // TCcQuery.Exec
#define IDH_HTML_TCcQuery_FieldExists_string               0x0000021E // TCcQuery.FieldExists@string
#define IDH_HTML_TCcQuery_FindField_string                 0x0000021F // TCcQuery.FindField@string
#define IDH_HTML_TCcQuery_FindMacro_string                 0x00000220 // TCcQuery.FindMacro@string
#define IDH_HTML_TCcQuery_FindParam_string                 0x00000221 // TCcQuery.FindParam@string
#define IDH_HTML_TCcQuery_MacroExists_string               0x00000222 // TCcQuery.MacroExists@string
#define IDH_HTML_TCcQuery_Next                             0x00000223 // TCcQuery.Next
#define IDH_HTML_TCcQuery_ParamExists_string               0x00000224 // TCcQuery.ParamExists@string
#define IDH_HTML_TCcQuery_Prepare                          0x00000225 // TCcQuery.Prepare
#define IDH_HTML_TCcQuery_UnPrepare                        0x00000226 // TCcQuery.UnPrepare
#define IDH_HTML_TCcQueryClient                            0x00000227 // TCcQueryClient
#define IDH_HTML_TCcQueryClient_Transport                  0x00000228 // TCcQueryClient.Transport
#define IDH_HTML_TCcQueryClient_Create_TCcConnection_TCcQuery_Integer_Boolean 0x00000229 // TCcQueryClient.Create@TCcConnection@TCcQuery@Integer@Boolean
#define IDH_HTML_TCcQueryClient_Destroy                    0x0000022A // TCcQueryClient.Destroy
#define IDH_HTML_TCcRecord                                 0x0000022B // TCcRecord
#define IDH_HTML_TCcRecord_Count                           0x0000022C // TCcRecord.Count
#define IDH_HTML_TCcRecord_FieldName                       0x0000022D // TCcRecord.FieldName
#define IDH_HTML_TCcRecord_Value                           0x0000022E // TCcRecord.Value
#define IDH_HTML_TCcRecord_Add_string                      0x0000022F // TCcRecord.Add@string
#define IDH_HTML_TCcRecord_Clear                           0x00000230 // TCcRecord.Clear
#define IDH_HTML_TCcRecord_Create                          0x00000231 // TCcRecord.Create
#define IDH_HTML_TCcRecord_Destroy                         0x00000232 // TCcRecord.Destroy
#define IDH_HTML_TCcRecord_FieldExists_string              0x00000233 // TCcRecord.FieldExists@string
#define IDH_HTML_TCcReplicator                             0x00000234 // TCcReplicator
#define IDH_HTML_TCcReplicator_LastResult                  0x00000235 // TCcReplicator.LastResult
#define IDH_HTML_TCcReplicator_AbortOnError                0x00000236 // TCcReplicator.AbortOnError
#define IDH_HTML_TCcReplicator_AutoClearMetadata           0x00000237 // TCcReplicator.AutoClearMetadata
#define IDH_HTML_TCcReplicator_AutoCommit                  0x00000238 // TCcReplicator.AutoCommit
#define IDH_HTML_TCcReplicator_AutoPriority                0x00000239 // TCcReplicator.AutoPriority
#define IDH_HTML_TCcReplicator_AutoReplicate               0x0000023A // TCcReplicator.AutoReplicate
#define IDH_HTML_TCcReplicator_BeforeReplicate             0x0000023B // TCcReplicator.BeforeReplicate
#define IDH_HTML_TCcReplicator_Busy                        0x0000023C // TCcReplicator.Busy
#define IDH_HTML_TCcReplicator_Closing                     0x0000023D // TCcReplicator.Closing
#define IDH_HTML_TCcReplicator_CommitOnFinished            0x0000023E // TCcReplicator.CommitOnFinished
#define IDH_HTML_TCcReplicator_ConfigurationName           0x0000023F // TCcReplicator.ConfigurationName
#define IDH_HTML_TCcReplicator_Direction                   0x00000240 // TCcReplicator.Direction
#define IDH_HTML_TCcReplicator_EmptyStringsToNull          0x00000241 // TCcReplicator.EmptyStringsToNull
#define IDH_HTML_TCcReplicator_ExtraFields                 0x00000242 // TCcReplicator.ExtraFields
#define IDH_HTML_TCcReplicator_FailIfNoPK                  0x00000243 // TCcReplicator.FailIfNoPK
#define IDH_HTML_TCcReplicator_Finished                    0x00000244 // TCcReplicator.Finished
#define IDH_HTML_TCcReplicator_HarmonizeFields             0x00000245 // TCcReplicator.HarmonizeFields
#define IDH_HTML_TCcReplicator_KeepConnection              0x00000246 // TCcReplicator.KeepConnection
#define IDH_HTML_TCcReplicator_LocalDB                     0x00000247 // TCcReplicator.LocalDB
#define IDH_HTML_TCcReplicator_LocalNode                   0x00000248 // TCcReplicator.LocalNode
#define IDH_HTML_TCcReplicator_Log                         0x00000249 // TCcReplicator.Log
#define IDH_HTML_TCcReplicator_LogErrors                   0x0000024A // TCcReplicator.LogErrors
#define IDH_HTML_TCcReplicator_MergeChangedFieldsOnConflict 0x0000024B // TCcReplicator.MergeChangedFieldsOnConflict
#define IDH_HTML_TCcReplicator_Nodes                       0x0000024C // TCcReplicator.Nodes
#define IDH_HTML_TCcReplicator_OnAutoCommit                0x0000024D // TCcReplicator.OnAutoCommit
#define IDH_HTML_TCcReplicator_OnCanReplicate              0x0000024E // TCcReplicator.OnCanReplicate
#define IDH_HTML_TCcReplicator_OnCommit                    0x0000024F // TCcReplicator.OnCommit
#define IDH_HTML_TCcReplicator_OnConflict                  0x00000250 // TCcReplicator.OnConflict
#define IDH_HTML_TCcReplicator_OnConnectionLost            0x00000251 // TCcReplicator.OnConnectionLost
#define IDH_HTML_TCcReplicator_OnConnectLocal              0x00000252 // TCcReplicator.OnConnectLocal
#define IDH_HTML_TCcReplicator_OnConnectRemote             0x00000253 // TCcReplicator.OnConnectRemote
#define IDH_HTML_TCcReplicator_OnDisconnect                0x00000254 // TCcReplicator.OnDisconnect
#define IDH_HTML_TCcReplicator_OnEmptyLog                  0x00000255 // TCcReplicator.OnEmptyLog
#define IDH_HTML_TCcReplicator_OnException                 0x00000256 // TCcReplicator.OnException
#define IDH_HTML_TCcReplicator_OnFinished                  0x00000257 // TCcReplicator.OnFinished
#define IDH_HTML_TCcReplicator_OnGenReplError              0x00000258 // TCcReplicator.OnGenReplError
#define IDH_HTML_TCcReplicator_OnGenReplicating            0x00000259 // TCcReplicator.OnGenReplicating
#define IDH_HTML_TCcReplicator_OnGetExtraFieldValue        0x0000025A // TCcReplicator.OnGetExtraFieldValue
#define IDH_HTML_TCcReplicator_OnGetFields                 0x0000025B // TCcReplicator.OnGetFields
#define IDH_HTML_TCcReplicator_OnKeySynchronized           0x0000025C // TCcReplicator.OnKeySynchronized
#define IDH_HTML_TCcReplicator_OnLogLoaded                 0x0000025D // TCcReplicator.OnLogLoaded
#define IDH_HTML_TCcReplicator_OnProgress                  0x0000025E // TCcReplicator.OnProgress
#define IDH_HTML_TCcReplicator_OnQueryDone                 0x0000025F // TCcReplicator.OnQueryDone
#define IDH_HTML_TCcReplicator_OnReplicateProc             0x00000260 // TCcReplicator.OnReplicateProc
#define IDH_HTML_TCcReplicator_OnReplicationAborted        0x00000261 // TCcReplicator.OnReplicationAborted
#define IDH_HTML_TCcReplicator_OnReplicationError          0x00000262 // TCcReplicator.OnReplicationError
#define IDH_HTML_TCcReplicator_OnReplicationResult         0x00000263 // TCcReplicator.OnReplicationResult
#define IDH_HTML_TCcReplicator_OnResolveConflict           0x00000264 // TCcReplicator.OnResolveConflict
#define IDH_HTML_TCcReplicator_OnRowBeforeReplicate        0x00000265 // TCcReplicator.OnRowBeforeReplicate
#define IDH_HTML_TCcReplicator_OnRowReplFinishing          0x00000266 // TCcReplicator.OnRowReplFinishing
#define IDH_HTML_TCcReplicator_OnRowReplicated             0x00000267 // TCcReplicator.OnRowReplicated
#define IDH_HTML_TCcReplicator_OnRowReplicating            0x00000268 // TCcReplicator.OnRowReplicating
#define IDH_HTML_TCcReplicator_OnRowReplicatingError       0x00000269 // TCcReplicator.OnRowReplicatingError
#define IDH_HTML_TCcReplicator_OnRowReplicatingQuery       0x0000026A // TCcReplicator.OnRowReplicatingQuery
#define IDH_HTML_TCcReplicator_OnTableBegin                0x0000026B // TCcReplicator.OnTableBegin
#define IDH_HTML_TCcReplicator_OnTableEnd                  0x0000026C // TCcReplicator.OnTableEnd
#define IDH_HTML_TCcReplicator_RecordChunks                0x0000026D // TCcReplicator.RecordChunks
#define IDH_HTML_TCcReplicator_RemoteDB                    0x0000026E // TCcReplicator.RemoteDB
#define IDH_HTML_TCcReplicator_RemoteNode                  0x0000026F // TCcReplicator.RemoteNode
#define IDH_HTML_TCcReplicator_ReplicateOnlyChangedFields  0x00000270 // TCcReplicator.ReplicateOnlyChangedFields
#define IDH_HTML_TCcReplicator_TableMapping                0x00000271 // TCcReplicator.TableMapping
#define IDH_HTML_TCcReplicator_TraceEvents                 0x00000272 // TCcReplicator.TraceEvents
#define IDH_HTML_TCcReplicator_TrimCharFields              0x00000273 // TCcReplicator.TrimCharFields
#define IDH_HTML_TCcReplicator_UsePKSynchronization        0x00000274 // TCcReplicator.UsePKSynchronization
#define IDH_HTML_TCcReplicator_Version                     0x00000275 // TCcReplicator.Version
#define IDH_HTML_TCcReplicator_AbortReplication            0x00000276 // TCcReplicator.AbortReplication
#define IDH_HTML_TCcReplicator_BatchImport_string_TCcSyncDirection_string_string_Boolean 0x00000277 // TCcReplicator.BatchImport@string@TCcSyncDirection@string@string@Boolean
#define IDH_HTML_TCcReplicator_ClearMetadataCache          0x00000278 // TCcReplicator.ClearMetadataCache
#define IDH_HTML_TCcReplicator_Connect                     0x00000279 // TCcReplicator.Connect
#define IDH_HTML_TCcReplicator_Create_TComponent           0x0000027A // TCcReplicator.Create@TComponent
#define IDH_HTML_TCcReplicator_Create_TComponent_string    0x0000027B // TCcReplicator.Create@TComponent@string
#define IDH_HTML_TCcReplicator_Destroy                     0x0000027C // TCcReplicator.Destroy
#define IDH_HTML_TCcReplicator_Disconnect                  0x0000027D // TCcReplicator.Disconnect
#define IDH_HTML_TCcReplicator_GetLocalTableName_string    0x0000027E // TCcReplicator.GetLocalTableName@string
#define IDH_HTML_TCcReplicator_GetRemoteTableName_string   0x0000027F // TCcReplicator.GetRemoteTableName@string
#define IDH_HTML_TCcReplicator_GetWhereValues_TCcQuery     0x00000280 // TCcReplicator.GetWhereValues@TCcQuery
#define IDH_HTML_TCcReplicator_RefreshDisplay              0x00000281 // TCcReplicator.RefreshDisplay
#define IDH_HTML_TCcReplicator_Replicate                   0x00000282 // TCcReplicator.Replicate
#define IDH_HTML_TCcReplicator_SynchronizeRows_string_string_TCcSyncDirection_Boolean 0x00000283 // TCcReplicator.SynchronizeRows@string@string@TCcSyncDirection@Boolean
#define IDH_HTML_TCcReplicatorList                         0x00000284 // TCcReplicatorList
#define IDH_HTML_TCcReplicatorList_BeforeReplicate         0x00000285 // TCcReplicatorList.BeforeReplicate
#define IDH_HTML_TCcReplicatorList_ConfigNames             0x00000286 // TCcReplicatorList.ConfigNames
#define IDH_HTML_TCcReplicatorList_CurrentReplicator       0x00000287 // TCcReplicatorList.CurrentReplicator
#define IDH_HTML_TCcReplicatorList_OnAbort                 0x00000288 // TCcReplicatorList.OnAbort
#define IDH_HTML_TCcReplicatorList_OnAutoCommit            0x00000289 // TCcReplicatorList.OnAutoCommit
#define IDH_HTML_TCcReplicatorList_OnCommit                0x0000028A // TCcReplicatorList.OnCommit
#define IDH_HTML_TCcReplicatorList_OnConflict              0x0000028B // TCcReplicatorList.OnConflict
#define IDH_HTML_TCcReplicatorList_OnConnectionLost        0x0000028C // TCcReplicatorList.OnConnectionLost
#define IDH_HTML_TCcReplicatorList_OnConnectLocal          0x0000028D // TCcReplicatorList.OnConnectLocal
#define IDH_HTML_TCcReplicatorList_OnConnectRemote         0x0000028E // TCcReplicatorList.OnConnectRemote
#define IDH_HTML_TCcReplicatorList_OnDisconnect            0x0000028F // TCcReplicatorList.OnDisconnect
#define IDH_HTML_TCcReplicatorList_OnEmptyLog              0x00000290 // TCcReplicatorList.OnEmptyLog
#define IDH_HTML_TCcReplicatorList_OnException             0x00000291 // TCcReplicatorList.OnException
#define IDH_HTML_TCcReplicatorList_OnFinished              0x00000292 // TCcReplicatorList.OnFinished
#define IDH_HTML_TCcReplicatorList_OnGenReplError          0x00000293 // TCcReplicatorList.OnGenReplError
#define IDH_HTML_TCcReplicatorList_OnGenReplicated         0x00000294 // TCcReplicatorList.OnGenReplicated
#define IDH_HTML_TCcReplicatorList_OnGenReplicating        0x00000295 // TCcReplicatorList.OnGenReplicating
#define IDH_HTML_TCcReplicatorList_OnGetFields             0x00000296 // TCcReplicatorList.OnGetFields
#define IDH_HTML_TCcReplicatorList_OnLogLoaded             0x00000297 // TCcReplicatorList.OnLogLoaded
#define IDH_HTML_TCcReplicatorList_OnProgress              0x00000298 // TCcReplicatorList.OnProgress
#define IDH_HTML_TCcReplicatorList_OnQueryDone             0x00000299 // TCcReplicatorList.OnQueryDone
#define IDH_HTML_TCcReplicatorList_OnReplicateProc         0x0000029A // TCcReplicatorList.OnReplicateProc
#define IDH_HTML_TCcReplicatorList_OnReplicationError      0x0000029B // TCcReplicatorList.OnReplicationError
#define IDH_HTML_TCcReplicatorList_OnRowBeforeReplicate    0x0000029C // TCcReplicatorList.OnRowBeforeReplicate
#define IDH_HTML_TCcReplicatorList_OnRowReplicated         0x0000029D // TCcReplicatorList.OnRowReplicated
#define IDH_HTML_TCcReplicatorList_OnRowReplicating        0x0000029E // TCcReplicatorList.OnRowReplicating
#define IDH_HTML_TCcReplicatorList_OnTableBegin            0x0000029F // TCcReplicatorList.OnTableBegin
#define IDH_HTML_TCcReplicatorList_OnTableEnd              0x000002A0 // TCcReplicatorList.OnTableEnd
#define IDH_HTML_TCcReplicatorList_ReplicatorCount         0x000002A1 // TCcReplicatorList.ReplicatorCount
#define IDH_HTML_TCcReplicatorList_Replicators             0x000002A2 // TCcReplicatorList.Replicators
#define IDH_HTML_TCcReplicatorList_Create_TComponent       0x000002A3 // TCcReplicatorList.Create@TComponent
#define IDH_HTML_TCcReplicatorList_Destroy                 0x000002A4 // TCcReplicatorList.Destroy
#define IDH_HTML_TCcServerTransport                        0x000002A5 // TCcServerTransport
#define IDH_HTML_TCcServerTransport_Connection             0x000002A6 // TCcServerTransport.Connection
#define IDH_HTML_TCcServerTransport_DatabaseAlias          0x000002A7 // TCcServerTransport.DatabaseAlias
#define IDH_HTML_TCcServerTransport_OnCloseSession         0x000002A8 // TCcServerTransport.OnCloseSession
#define IDH_HTML_TCcServerTransport_OnNewSession           0x000002A9 // TCcServerTransport.OnNewSession
#define IDH_HTML_TCcServerTransport_Password               0x000002AA // TCcServerTransport.Password
#define IDH_HTML_TCcServerTransport_Session                0x000002AB // TCcServerTransport.Session
#define IDH_HTML_TCcServerTransport_SessionCount           0x000002AC // TCcServerTransport.SessionCount
#define IDH_HTML_TCcServerTransport_SessionTimeout         0x000002AD // TCcServerTransport.SessionTimeout
#define IDH_HTML_TCcServerTransport_Create_TComponent      0x000002AE // TCcServerTransport.Create@TComponent
#define IDH_HTML_TCcServerTransport_Destroy                0x000002AF // TCcServerTransport.Destroy
#define IDH_HTML_TCcServerTransport_FindSession_string     0x000002B0 // TCcServerTransport.FindSession@string
#define IDH_HTML_TCcServerTransport_StartServer            0x000002B1 // TCcServerTransport.StartServer
#define IDH_HTML_TCcServerTransport_StopServer             0x000002B2 // TCcServerTransport.StopServer
#define IDH_HTML_TCcSession                                0x000002B3 // TCcSession
#define IDH_HTML_TCcSession_ClientCopyCatVersion           0x000002B4 // TCcSession.ClientCopyCatVersion
#define IDH_HTML_TCcSession_Connection                     0x000002B5 // TCcSession.Connection
#define IDH_HTML_TCcSession_SessionID                      0x000002B6 // TCcSession.SessionID
#define IDH_HTML_TCcSession_Create_string_TCcConnection    0x000002B7 // TCcSession.Create@string@TCcConnection
#define IDH_HTML_TCcSession_Destroy                        0x000002B8 // TCcSession.Destroy
#define IDH_HTML_TCcSQLiteAdaptor                          0x000002B9 // TCcSQLiteAdaptor
#define IDH_HTML_TCcSQLiteAdaptor_CheckCustomMetadata      0x000002BA // TCcSQLiteAdaptor.CheckCustomMetadata
#define IDH_HTML_TCcSQLiteAdaptor_ConvertValue_Variant_TFieldType 0x000002BB // TCcSQLiteAdaptor.ConvertValue@Variant@TFieldType
#define IDH_HTML_TCcSQLiteAdaptor_Create_TCcConnection     0x000002BC // TCcSQLiteAdaptor.Create@TCcConnection
#define IDH_HTML_TCcSQLiteAdaptor_DeclareField_String_TFieldType_Integer_Boolean_Boolean_Boolean 0x000002BD // TCcSQLiteAdaptor.DeclareField@String@TFieldType@Integer@Boolean@Boolean@Boolean
#define IDH_HTML_TCcSQLiteAdaptor_Destroy                  0x000002BE // TCcSQLiteAdaptor.Destroy
#define IDH_HTML_TCcSQLiteAdaptor_GenDeclared_String       0x000002BF // TCcSQLiteAdaptor.GenDeclared@String
#define IDH_HTML_TCcSQLiteAdaptor_GenerateTriggers_TCcQuery_TCcQuery_Boolean_Boolean 0x000002C0 // TCcSQLiteAdaptor.GenerateTriggers@TCcQuery@TCcQuery@Boolean@Boolean
#define IDH_HTML_TCcSQLiteAdaptor_GetAdaptorName           0x000002C1 // TCcSQLiteAdaptor.GetAdaptorName
#define IDH_HTML_TCcSQLiteAdaptor_GrantRightsToTable_String 0x000002C2 // TCcSQLiteAdaptor.GrantRightsToTable@String
#define IDH_HTML_TCcSQLiteAdaptor_RemoveTriggers_TCcQuery  0x000002C3 // TCcSQLiteAdaptor.RemoveTriggers@TCcQuery
#define IDH_HTML_TCcSQLiteAdaptor_SQLFormatValue_Variant_TFieldType 0x000002C4 // TCcSQLiteAdaptor.SQLFormatValue@Variant@TFieldType
#define IDH_HTML_TCcSQLiteAdaptor_SupportsGenerators       0x000002C5 // TCcSQLiteAdaptor.SupportsGenerators
#define IDH_HTML_TCcSqlParser                              0x000002C6 // TCcSqlParser
#define IDH_HTML_TCcSqlParser_Offset                       0x000002C7 // TCcSqlParser.Offset
#define IDH_HTML_TCcSqlParser_QuoteCount                   0x000002C8 // TCcSqlParser.QuoteCount
#define IDH_HTML_TCcSqlParser_Token                        0x000002C9 // TCcSqlParser.Token
#define IDH_HTML_TCcSqlParser_TokenChar                    0x000002CA // TCcSqlParser.TokenChar
#define IDH_HTML_TCcSqlParser_TokenCount                   0x000002CB // TCcSqlParser.TokenCount
#define IDH_HTML_TCcSqlParser_Create                       0x000002CC // TCcSqlParser.Create
#define IDH_HTML_TCcSqlParser_Destroy                      0x000002CD // TCcSqlParser.Destroy
#define IDH_HTML_TCcSqlParser_Parse_string                 0x000002CE // TCcSqlParser.Parse@string
#define IDH_HTML_TCcSQLServerAdaptor                       0x000002CF // TCcSQLServerAdaptor
#define IDH_HTML_TCcSQLServerAdaptor_CheckCustomMetadata   0x000002D0 // TCcSQLServerAdaptor.CheckCustomMetadata
#define IDH_HTML_TCcSQLServerAdaptor_Create_TCcConnection  0x000002D1 // TCcSQLServerAdaptor.Create@TCcConnection
#define IDH_HTML_TCcSQLServerAdaptor_CreateProcedures      0x000002D2 // TCcSQLServerAdaptor.CreateProcedures
#define IDH_HTML_TCcSQLServerAdaptor_DeclareField_String_TFieldType_Integer_Boolean_Boolean_Boolean 0x000002D3 // TCcSQLServerAdaptor.DeclareField@String@TFieldType@Integer@Boolean@Boolean@Boolean
#define IDH_HTML_TCcSQLServerAdaptor_DeclareGenerator_String 0x000002D4 // TCcSQLServerAdaptor.DeclareGenerator@String
#define IDH_HTML_TCcSQLServerAdaptor_Destroy               0x000002D5 // TCcSQLServerAdaptor.Destroy
#define IDH_HTML_TCcSQLServerAdaptor_DropProcedures        0x000002D6 // TCcSQLServerAdaptor.DropProcedures
#define IDH_HTML_TCcSQLServerAdaptor_GenDeclared_String    0x000002D7 // TCcSQLServerAdaptor.GenDeclared@String
#define IDH_HTML_TCcSQLServerAdaptor_GenerateTriggers_TCcQuery_TCcQuery_Boolean_Boolean 0x000002D8 // TCcSQLServerAdaptor.GenerateTriggers@TCcQuery@TCcQuery@Boolean@Boolean
#define IDH_HTML_TCcSQLServerAdaptor_GetAdaptorName        0x000002D9 // TCcSQLServerAdaptor.GetAdaptorName
#define IDH_HTML_TCcSQLServerAdaptor_GetGenerator_String_Integer 0x000002DA // TCcSQLServerAdaptor.GetGenerator@String@Integer
#define IDH_HTML_TCcSQLServerAdaptor_GetGeneratorValue_String_Integer 0x000002DB // TCcSQLServerAdaptor.GetGeneratorValue@String@Integer
#define IDH_HTML_TCcSQLServerAdaptor_RemoveCustomMetadata  0x000002DC // TCcSQLServerAdaptor.RemoveCustomMetadata
#define IDH_HTML_TCcSQLServerAdaptor_RemoveTriggers_TCcQuery 0x000002DD // TCcSQLServerAdaptor.RemoveTriggers@TCcQuery
#define IDH_HTML_TCcSQLServerAdaptor_SQLFormatValue_Variant_TFieldType 0x000002DE // TCcSQLServerAdaptor.SQLFormatValue@Variant@TFieldType
#define IDH_HTML_TCcSQLServerAdaptor_SupportsGenerators    0x000002DF // TCcSQLServerAdaptor.SupportsGenerators
#define IDH_HTML_TCcStringList                             0x000002E0 // TCcStringList
#define IDH_HTML_TCcStringList_SQLCommaText                0x000002E1 // TCcStringList.SQLCommaText
#define IDH_HTML_TCcValue                                  0x000002E2 // TCcValue
#define IDH_HTML_TCcValue_AsArray                          0x000002E3 // TCcValue.AsArray
#define IDH_HTML_TCcValue_AsField                          0x000002E4 // TCcValue.AsField
#define IDH_HTML_TCcValue_Value                            0x000002E5 // TCcValue.Value
#define IDH_HTML_TCcValue_ValueType                        0x000002E6 // TCcValue.ValueType
#define IDH_HTML_TCcValue_Assign_TCcValue                  0x000002E7 // TCcValue.Assign@TCcValue
#define IDH_HTML_TCcValue_Clear                            0x000002E8 // TCcValue.Clear
#define IDH_HTML_TCcValue_Create                           0x000002E9 // TCcValue.Create
#define IDH_HTML_TCcValue_Destroy                          0x000002EA // TCcValue.Destroy
#define IDH_HTML_TCcValue_SetValueAsType_Variant_TFieldType 0x000002EB // TCcValue.SetValueAsType@Variant@TFieldType
#define IDH_HTML_TCcWideMemoField                          0x000002EC // TCcWideMemoField
#define IDH_HTML_TPeriodicity                              0x000002ED // TPeriodicity
#define IDH_HTML_TPeriodicity_Frequency                    0x000002EE // TPeriodicity.Frequency
#define IDH_HTML_TPeriodicity_Create_TComponent            0x000002EF // TPeriodicity.Create@TComponent
#define IDH_HTML_TPeriodicity_Destroy                      0x000002F0 // TPeriodicity.Destroy
#define IDH_HTML_TPeriodicity_Start                        0x000002F1 // TPeriodicity.Start
#define IDH_HTML_TPeriodicity_Stop                         0x000002F2 // TPeriodicity.Stop
#define IDH_HTML_ExtractItemsInCommon_TStringList_TStringList_TStringList 0x000002F3 // ExtractItemsInCommon@TStringList@TStringList@TStringList
#define IDH_HTML_GetDBConnectorClass_string                0x000002F4 // GetDBConnectorClass@string
#define IDH_HTML_ParseKeyValues_String_Integer_Boolean     0x000002F5 // ParseKeyValues@String@Integer@Boolean
#define IDH_HTML_ReadBinaryStream_TCustomIniFile_string_string_TStream 0x000002F6 // ReadBinaryStream@TCustomIniFile@string@string@TStream
#define IDH_HTML_RegisterDBConnector_TCcConnectionClass_string 0x000002F7 // RegisterDBConnector@TCcConnectionClass@string
#define IDH_HTML_RemoveItemsInCommon_TStringList_TStringList 0x000002F8 // RemoveItemsInCommon@TStringList@TStringList
#define IDH_HTML_RxAssignRecord_TDataSet_TDataSet_Boolean  0x000002F9 // RxAssignRecord@TDataSet@TDataSet@Boolean
#define IDH_HTML_WriteBinaryStream_TCustomIniFile_string_string_TStream 0x000002FA // WriteBinaryStream@TCustomIniFile@string@string@TStream
#define IDH_HTML_TCcCommitType                             0x000002FB // TCcCommitType
#define IDH_HTML_TCcFieldType                              0x000002FC // TCcFieldType
#define IDH_HTML_TCcInterbaseBranch                        0x000002FD // TCcInterbaseBranch
#define IDH_HTML_TCcKeyOrigin                              0x000002FE // TCcKeyOrigin
#define IDH_HTML_TCcLogState                               0x000002FF // TCcLogState
#define IDH_HTML_TCcQueryResult                            0x00000300 // TCcQueryResult
#define IDH_HTML_TCcQueryType                              0x00000301 // TCcQueryType
#define IDH_HTML_TCcRemoteFunction                         0x00000302 // TCcRemoteFunction
#define IDH_HTML_TCcReplicationResult                      0x00000303 // TCcReplicationResult
#define IDH_HTML_TCcReplicationResultType                  0x00000304 // TCcReplicationResultType
#define IDH_HTML_TCcSyncDirection                          0x00000305 // TCcSyncDirection
#define IDH_HTML_TCcSysTable                               0x00000306 // TCcSysTable
#define IDH_HTML_TCcTraceType                              0x00000307 // TCcTraceType
#define IDH_HTML_TCcValueType                              0x00000308 // TCcValueType
#define IDH_HTML_TConflictRecord                           0x00000309 // TConflictRecord
#define IDH_HTML_PByte                                     0x0000030A // PByte
#define IDH_HTML_PCcMemBuffer                              0x0000030B // PCcMemBuffer
#define IDH_HTML_TCcAfterReplicationEvent                  0x0000030C // TCcAfterReplicationEvent
#define IDH_HTML_TCcCanReplicateEvent                      0x0000030D // TCcCanReplicateEvent
#define IDH_HTML_TCcConnectionClass                        0x0000030E // TCcConnectionClass
#define IDH_HTML_TCcDBAdaptorClass                         0x0000030F // TCcDBAdaptorClass
#define IDH_HTML_TCcErrorEvent                             0x00000310 // TCcErrorEvent
#define IDH_HTML_TCcExceptionEvent                         0x00000311 // TCcExceptionEvent
#define IDH_HTML_TCcExceptionNotifyEvent                   0x00000312 // TCcExceptionNotifyEvent
#define IDH_HTML_TCcFieldTypes                             0x00000313 // TCcFieldTypes
#define IDH_HTML_TCcFieldValueEvent                        0x00000314 // TCcFieldValueEvent
#define IDH_HTML_TCcGetFieldsEvent                         0x00000315 // TCcGetFieldsEvent
#define IDH_HTML_TCcLogListEvent                           0x00000316 // TCcLogListEvent
#define IDH_HTML_TCcLostConnectEvent                       0x00000317 // TCcLostConnectEvent
#define IDH_HTML_TCcNameEvent                              0x00000318 // TCcNameEvent
#define IDH_HTML_TCcNotifyEvent                            0x00000319 // TCcNotifyEvent
#define IDH_HTML_TCcOperationEvent                         0x0000031A // TCcOperationEvent
#define IDH_HTML_TCcQueryEvent                             0x0000031B // TCcQueryEvent
#define IDH_HTML_TCcQueryTypes                             0x0000031C // TCcQueryTypes
#define IDH_HTML_TCcReplicateRowErrorEvent                 0x0000031D // TCcReplicateRowErrorEvent
#define IDH_HTML_TCcReplicationEvent                       0x0000031E // TCcReplicationEvent
#define IDH_HTML_TCcReplicationQueryEvent                  0x0000031F // TCcReplicationQueryEvent
#define IDH_HTML_TCcScriptEvent                            0x00000320 // TCcScriptEvent
#define IDH_HTML_TCcSessionEvent                           0x00000321 // TCcSessionEvent
#define IDH_HTML_TConfirmEvent                             0x00000322 // TConfirmEvent
#define IDH_HTML_TConflictEvent                            0x00000323 // TConflictEvent
#define IDH_HTML_TGenReplEvent                             0x00000324 // TGenReplEvent
#define IDH_HTML_FieldTypeCount                            0x00000325 // FieldTypeCount
#define IDH_HTML_IB_SQL_ARRAY                              0x00000326 // IB_SQL_ARRAY
#define IDH_HTML_IB_SQL_BLOB                               0x00000327 // IB_SQL_BLOB
#define IDH_HTML_IB_SQL_BOOLEAN                            0x00000328 // IB_SQL_BOOLEAN
#define IDH_HTML_IB_SQL_D_FLOAT                            0x00000329 // IB_SQL_D_FLOAT
#define IDH_HTML_IB_SQL_DATE                               0x0000032A // IB_SQL_DATE
#define IDH_HTML_IB_SQL_DOUBLE                             0x0000032B // IB_SQL_DOUBLE
#define IDH_HTML_IB_SQL_FLOAT                              0x0000032C // IB_SQL_FLOAT
#define IDH_HTML_IB_SQL_INT64                              0x0000032D // IB_SQL_INT64
#define IDH_HTML_IB_SQL_LONG                               0x0000032E // IB_SQL_LONG
#define IDH_HTML_IB_SQL_QUAD                               0x0000032F // IB_SQL_QUAD
#define IDH_HTML_IB_SQL_SHORT                              0x00000330 // IB_SQL_SHORT
#define IDH_HTML_IB_SQL_TEXT                               0x00000331 // IB_SQL_TEXT
#define IDH_HTML_IB_SQL_TIMESTAMP                          0x00000332 // IB_SQL_TIMESTAMP
#define IDH_HTML_IB_SQL_TYPE_DATE                          0x00000333 // IB_SQL_TYPE_DATE
#define IDH_HTML_IB_SQL_TYPE_TIME                          0x00000334 // IB_SQL_TYPE_TIME
#define IDH_HTML_IB_SQL_VARYING                            0x00000335 // IB_SQL_VARYING
#define IDH_HTML_VersionNumber                             0x00000336 // VersionNumber
#define IDH_HTML_CCat_pas                                  0x00000337 // CCat.pas
#define IDH_HTML_CcConf_pas                                0x00000338 // CcConf.pas
#define IDH_HTML_CcConflictMgr_pas                         0x00000339 // CcConflictMgr.pas
#define IDH_HTML_CcDB_pas                                  0x0000033A // CcDB.pas
#define IDH_HTML_CcEditors_pas                             0x0000033B // CcEditors.pas
#define IDH_HTML_CcInterbase_pas                           0x0000033C // CcInterbase.pas
#define IDH_HTML_CcInterbaseConn_pas                       0x0000033D // CcInterbaseConn.pas
#define IDH_HTML_CcKeys_pas                                0x0000033E // CcKeys.pas
#define IDH_HTML_CcLog_pas                                 0x0000033F // CcLog.pas
#define IDH_HTML_CcMemDS_pas                               0x00000340 // CcMemDS.pas
#define IDH_HTML_CcMySQL_pas                               0x00000341 // CcMySQL.pas
#define IDH_HTML_CcNexusDB_pas                             0x00000342 // CcNexusDB.pas
#define IDH_HTML_CcOracle_pas                              0x00000343 // CcOracle.pas
#define IDH_HTML_CcPostgres_pas                            0x00000344 // CcPostgres.pas
#define IDH_HTML_CcProviders_pas                           0x00000345 // CcProviders.pas
#define IDH_HTML_CcReplicator_pas                          0x00000346 // CcReplicator.pas
#define IDH_HTML_CcRplList_pas                             0x00000347 // CcRplList.pas
#define IDH_HTML_CcSQLite_pas                              0x00000348 // CcSQLite.pas
#define IDH_HTML_CcSQLServer_pas                           0x00000349 // CcSQLServer.pas
#define IDH_HTML_CcTransports_pas                          0x0000034A // CcTransports.pas
