<?php
 return array (
  '"%s" can be ordered along with these products/subscripton(s) only: %s' => '"%s" ne peut être commandé que avec ces produits/abonnements: %s',
  '"%s" can only be ordered if you have expired subscription(s) for these products: %s' => '"%s" ne peut être commandé si votre abonnement a expiré pour ces produits: %s',
  '"%s" cannot be ordered because you have active subscription(s) to: %s' => '"%s" ne peut être commandé parce que les abonnements à %s sont actifs

.',
  '"%s" cannot be ordered because you have expired subscription(s) to: %s' => '"%s" ne peut être commandé parce que les abonnements à %s ont expiré.',
  '%s Configuration' => 'Configuration %s',
  '%s database and tables prefix' => 'Base de données %s et préfixes de tables',
  '(must match your credit card statement delivery address)' => '(doit
 correspondre à l\'adresse de livraison de votre facture carte bancaire)',
  'Access Denied' => 'Accès refusé',
  'Access Log' => 'Enregistrement des accès',
  'Access Permissions' => 'Permissions d\'accès',
  'Actions' => 'Actions',
  'Active Users' => 'Utilisateurs actifs',
  'Add to Basket' => 'Ajouter au panier',
  'Add/Renew Subscription' => 'Ajouter/renouveler un abonnement',
  'Address Info' => 'Information adresse',
  'Address Information' => 'Informations d\'adresse',
  'Administrator' => 'Administrateur',
  'Advertise our website to your friends and earn money' => 'Parlez de notre site à vos amis et gagnez de l\'argent',
  'Affiliate Clicks/Sales Statistics' => 'Clics affiliés/Statistiques de vente',
  'Affiliate Info' => 'Informations de l\'affilié',
  'Affiliate Payout Type' => 'Type de paiement affilié',
  'Affiliate Program' => 'Programme affilié',
  'Affiliate Signup Form' => 'Formulaire d\'inscription affilié',
  'Affiliate info' => 'information de la filiale',
  'Affiliate stats' => 'Statistiques de filiale',
  'Affiliates' => 'Affilié',
  'All Affiliates' => 'Tous les affiliés',
  'All Users' => 'Tous les utilisateurs',
  'All records' => 'Tous les enregistrements',
  'Amount' => 'Montant',
  'An Error has occurred' => 'Une erreur est survenue',
  'An account with the same email already exists.' => 'Un compte avec la même adresse email existe déjà.',
  'An error occurred while handling your payment.' => 'Une erreur est survenue à votre paiement',
  'An internal error happened in the script, please contact webmaster for details' => 'Une erreur interne est survenue dans ce script. Contactez le webmaster',
  'Any product' => 'N\'importe quel produit',
  'Apply' => 'Appliquer',
  'Apply Filter' => 'Appliquer le filtre',
  'Attachments' => 'Pièces jointes',
  'Authentication' => 'Authentification',
  'Authentication problem, please contact website administator' => 'Problème d\'authentification, contactez l\'administrateur du site',
  'Available Bricks (drag to left to add)' => 'Briques disponibles (faites glisser vers la gauche pour ajouter)',
  'Awaiting Admin Response' => 'En attente de la réponse de l\'administrateur',
  'Awaiting User Response' => 'En attente de la réponse de l\'utilisateur',
  'Back' => 'Retour',
  'Back to shopping cart' => 'Retour au panier',
  'Bank Identification' => 'Identifiant de la banque',
  'Bank Name' => 'Nom de la banque',
  'Bank Phone' => 'Téléphone de la banque',
  'Banners and Links' => 'Bannières et liens',
  'Billing International Province' => 'Province internationale de facturation',
  'Both Affiliate and member' => 'Affilié et membre',
  'CC Demo' => 'Démo CC',
  'COUPONS' => 'COUPONS',
  'CSRF protection error - form must be submitted within %d minutes after displaying, please repeat' => 'Erreur de protection CSRF - le formulaire doit être à nouveau soumis moins de %d minutes après affichage, veuillez recommencer',
  'Can open and answer helpdesk tickets' => 'Peut ouvrir et répondre aux tickets du bureau d\'aide',
  'Can view/edit customer Credit Card information and rebills' => 'Possibilité de voir/éditer les informations de carte de crédit clients et de refacturer',
  'Cancel' => 'Annuler',
  'Cancel Subscription' => 'Annuler l\'abonnement',
  'Cancelled' => 'annulé',
  'Cannot use FREE payment plugin with the product which cost more than 0.0' => 'Vous ne pouvez pas utiliser le plugin de paiement FREE pour un produit qui coûte plus de 0.0',
  'Card Expire' => 'Expiration de la carte',
  'Card Issue #' => 'Problème carte #',
  'Card Start Date' => 'Date de début de carte',
  'Cardholder Name' => 'Nom du propriétaire de la carte',
  'Category' => 'Catégorie',
  'Change' => 'Changer',
  'Change Password' => 'Changez le mot de passe',
  'Change Password error' => 'Erreur de changement de mot de passe',
  'Change Password/Edit Profile' => 'Changez votre mot de passe/Éditer votre profil',
  'Change Subscription' => 'Changer l\'abonnement',
  'Change Username' => 'Changer le nom d\'utilisateur',
  'Change payout info' => 'Changez les informations de paiement',
  'Checkout' => 'Facturation',
  'Checkout error: ' => 'Erreur de facturation',
  'Choose Action' => 'Choisir action',
  'Choose Payment System' => 'Choisir un mode de paiement',
  'Choose a Password
must be %d or more characters' => 'Choisissez un mot de passe
il doit contenir %d caractères ou plus',
  'Choose a Username
it must be %d or more characters in length
may only contain letters, numbers, and underscores' => 'Choisissez un nom d\'utilisateur
il doit contenir %d caractères ou plus
ne peut contenir que des lettres, chiffres et underscores',
  'Choose another payment processor and try again' => 'Choisissez une autre méthode de paiement et recommencez',
  'City' => 'Ville',
  'Click here if you do not want to wait any longer (or if your browser does not automatically forward you).' => 'Cliquez ici si vous ne voulez pas attendre plus longtemps (ou si votre navigateur ne vous redirige pas automatiquement)',
  'Clicks' => 'Clics',
  'Close' => 'Fermer',
  'Close Ticket' => 'Fermer un ticket',
  'Closed' => 'Fermé',
  'Comment' => 'Commentaire',
  'Commission earned' => 'Commission gagnée',
  'Company Name' => 'Nom de la compagnie',
  'Confirm New Password' => 'Confirmez le nouveau mot de passe',
  'Confirm Password' => 'Confirmez le mot de passe',
  'Confirm Payment' => 'Confirmer le paiement',
  'Confirm Your Password' => 'Confirmez votre mot de passe',
  'Continue' => 'Continuer',
  'Conversation' => 'Conversation',
  'Country' => 'Pays',
  'Coupon' => 'Coupon',
  'Coupon Discount' => 'Coupon de réduction',
  'Coupon code disabled' => 'Code coupon désactivé',
  'Coupon code expired' => 'Code coupon expiré',
  'Coupon is not yet active' => 'Le coupon n\'est pas encore actif',
  'Coupon usage limit exceeded' => 'Limite d\'utilisation du coupon dépassée',
  'Credit Card Code' => 'Code de carte de crédit',
  'Credit Card Info' => 'Informations de carte de crédit',
  'Credit Card Number' => 'Numéro de carte de crédit',
  'Credit Card Rebills' => 'Refacturations de la carte de crédit',
  'Credit Card Type' => 'Type de carte de crédit',
  'Credit Cards' => 'Cartes de crédit',
  'Current password entered incorrectly, please try again' => 'Le mot de passe actuel n\'a pas été saisi correctement, veuillez réessayer',
  'Custom Commission' => 'Commission client',
  'DONE' => 'FAIT',
  'Date' => 'Date',
  'Date and time of payment: %s' => 'Date et heure de paiement: %s',
  'Date must be in format %s' => 'La date doit être en format %s',
  'Day' => 'Jour',
  'Days' => 'Jours',
  'Default Level
default level - user reset to this access level
if no active subscriptions exists
(for example all subscriptions expired)' => 'Niveau par défaut
Niveau par défaut - utilisateur réinitialisé à ce niveau d\'accès
si aucun abonnement n\'existe
(par exemple, tous les abonnements ont expiré)',
  'Delete' => 'Supprimer',
  'Delete %s' => 'Supprimer %s',
  'Description' => 'Description',
  'Discard' => 'Annuler',
  'Discount' => 'réduction',
  'Do you really want to %s %s %s records' => 'Souhaitez-vous réellement %s %s %s les enregistrements ?',
  'Do you really want to %s?' => 'Voulez-vous vraiment %s?',
  'Do you really want to cancel subscription?' => 'Voulez-vous réellement annuler votre abonnement?',
  'Do you really want to delete record?' => 'Souhaitez-vous réellement effacer l\'enregistrement ?',
  'E-Mail' => 'Email',
  'E-Mail Address' => 'Adresse email',
  'E-Mail Address or Username' => 'Adresse mail ou nom d\'utilisateur',
  'E-Mail Format' => 'Format d\'email',
  'E-Mail Verification' => 'Vérification de l\'email',
  'Edit' => 'Éditer',
  'Edit %s' => 'Modifier %s',
  'Edit Brick Labels' => 'Modifier les noms des briques',
  'Edit E-Mail Template' => 'Éditer le modèle d\'email',
  'Edit Profile' => 'Éditer le profil',
  'End' => 'Fin',
  'Enter Coupon Code:' => 'Entrez le code coupon',
  'Enter Verification Text
please type text from image' => 'Entrez le texte de vérification
veuillez saisir le texte de l\'image',
  'Enter your E-Mail Address or Username' => 'Entrez votre adresse email ou nom d\'utilisateur',
  'Error 404 - Not Found' => 'Erreur 404 - non trouvé',
  'Expired Users' => 'Utilisateurs expirés',
  'Export' => 'Exporter',
  'Export Format' => 'Format de l\'exportation',
  'Field Updated' => 'Champ mis à jour',
  'Fields To Export' => 'Champs à exporter',
  'Filter' => 'Filtrez',
  'Filter by String' => 'Filtrer par chaine',
  'First & Last Name' => 'Prénom et nom de famille',
  'Form Bricks' => 'Former des briques',
  'Form Page Break' => 'Former une séparation de page',
  'Free' => 'Vide',
  'Free Access' => 'Accès libre',
  'Get Password' => 'Trouvez un mot de passe',
  'Get affiliate banners and links' => 'Obtenir des bannières et liens',
  'HTML Message' => 'Message HTML',
  'Having Active Subscription To:' => 'Avoir un abonnement actif à :',
  'Having Expired Subscription To:' => 'Avoir un abonnement expiré à :',
  'Helpdesk' => 'Bureau d\'aide',
  'Housenumber' => 'Numéro de maison',
  'I Agree' => 'J\'accepte',
  'Integer value required' => 'Valeur entière requise',
  'Invalid Credit Card Number' => 'Numéro de carte de crédit invalide',
  'Invalid Expiration Date - Month' => 'Date d\'expiration invalide - mois',
  'Invalid Expiration Date - Year' => 'Date d\'expiration invalide - année',
  'Invalid Issue Number' => 'Numéro de problème invalide',
  'Invoice' => 'Facture',
  'Invoice not found' => 'Facture introuvable',
  'Is Affiliate?' => 'Est affilié ?',
  'Item' => 'Objet',
  'Language' => 'Langue',
  'Lifetime' => 'Vie',
  'Link' => 'Lien',
  'Live Edit %s' => 'Modification en direct %s',
  'Logged in as %s' => 'Connecté en tant que %s',
  'Login' => 'Se connecter',
  'Logout' => 'Se déconnecter',
  'Lost Password Sending Error' => 'Erreur d\'envoi du mot de passe perdu',
  'Lost Password Sent' => 'Mot de passe perdu envoyé',
  'Lost password' => 'Mot de passe perdu',
  'Main Page' => 'Page principale',
  'Make Payment' => 'Faire un paiement',
  'Manage Banners and Text Links' => 'Gérer les bannières et liens texte',
  'Manage Newsletters' => 'Gérer les lettres d\'informations',
  'Marketing Materials' => 'Matériaux marketing',
  'Member Login' => 'Nom de membre',
  'Membership Type' => 'Type d\'abonnement',
  'Message' => 'Message',
  'Message can not be empty' => 'Le message ne peut pas être vide',
  'Month' => 'Mois',
  'Months' => 'Mois',
  'Multiplier' => 'Multiplicateur',
  'Name' => 'Nom',
  'New' => 'Nouveau',
  'New %s' => 'Nouveau %s',
  'New Password' => 'Nouveau mot de passe',
  'New Password
you can choose new password here or keep it unchanged
must be %d or more characters' => 'Nouveau mot de passe
vous pouvez choisir un nouveau mot de passe, ou conserver le même
il doit contenir %d caractères ou plus',
  'Newsletter' => 'Lettre d\'information',
  'Newsletter Subscriptions' => 'Inscriptions newsletter',
  'Next' => 'Suivant',
  'No' => 'Non',
  'No Banners and Links added by admin yet' => 'Aucune bannière ni lien encore ajoutés par l\'administrateur',
  'No commissions on this date' => 'Aucune commission à ce jour',
  'No coupons found with such coupon code' => 'Aucun coupon trouvé avec ce code',
  'No items selected for purchase' => 'Aucun objet sélectionné pour achat',
  'No records found' => 'Aucun dossier trouvé',
  'No, cancel' => 'No, annuler',
  'No, please keep me subscribed' => 'Non, je veux être encore inscrit',
  'Not Selected' => 'Non sélectionné',
  'Not registered yet?' => 'Pas encore enregistré',
  'Numeric value required' => 'Valeur numérique requise',
  'Offline Payment' => 'Paiement hors ligne',
  'Only Affiliate %s(rarely used)%s' => 'Affilier seulement %s (rarement utilisé) %s',
  'Order reference: %s' => 'Référence de commande: %s',
  'PDF Invoice' => 'Facture PDF',
  'Password' => 'Mot de passe',
  'Password and Password Confirmation are different. Please reenter both' => 'Le mot de passe et la confirmation du mot de passe sont différents. Veuillez saisir à nouveau les deux',
  'Password must contain at least %d letters or digits' => 'Le mot de passe doit contenir au moins %d lettres ou chiffres',
  'Passwords do not match' => 'Les mots de passe ne correspondent pas',
  'Path to %s' => 'Chemin vers %s',
  'Path to %s Folder' => 'Chemin vers le dossier %s',
  'Payment Error' => 'Erreur de paiement',
  'Payment Failed' => 'Échec du paiement',
  'Payment System' => 'Système de paiement',
  'Payment System Description' => 'Description du système de paiement',
  'Payment System Title' => 'Titre du système de paiement',
  'Payment error: ' => 'Erreur de paiement',
  'Payment failed' => 'Échec du paiement',
  'Payments' => 'Paiements',
  'Payments History' => 'Historique de paiement',
  'Period must be in interval 1-24 months' => 'Les périodes doivent être entre 1 et 24 mois',
  'Period must be in interval 1-5 years' => 'Les périodes doivent être entre 1 et 5 ans.',
  'Period must be in interval 1-90 days' => 'Les périodes doivent être entre 1 et 90 jours',
  'Phone' => 'Numéro de téléphone',
  'Plain-Text Message' => 'Message en texte',
  'Please %slogin%s to your existing account.%sIf you have not completed payment, you will be able to complete it after login' => 'Veuillez %s vous connecter %s à votre compte existant. %s Si vous n\'avez pas effectué le paiement, vous pourrez le compléter après la connexion',
  'Please Select' => 'Veuillez sélectionner',
  'Please agree to User Agreement' => 'Veuillez accepter l\'Accord utilisateur',
  'Please check your email - verification email message has been just emailed to you. Once you receive this message, read this and follow instructions in this email to complete your subscription.' => 'Vérifier votre email - un email de vérification vient de vous être envoyé. Une fois que vous recevrez ce message, lisez-le et suivez les instructions pour finir votre abonnement.',
  'Please check your mailbox' => 'Veuillez vérifier votre boîte aux lettres',
  'Please choose' => 'Veuillez choisir',
  'Please choose a Credit Card Type' => 'Veuillez choisir un type de carte de crédit',
  'Please choose a membership type' => 'Veuillez choisir un type d\'abonnement',
  'Please choose a payment system' => 'Veuillez choisir un système de paiement',
  'Please choose state' => 'Choisir l\'état',
  'Please enter %s' => 'Veuillez saisir %s',
  'Please enter City' => 'Entrez le nom de la ville',
  'Please enter Country' => 'Entrez le pays',
  'Please enter Credit Card Code' => 'Veuillez entre le code de carte de crédit',
  'Please enter Credit Card Number' => 'Entrez votre numéro de carte de crédit',
  'Please enter Password' => 'Veuillez saisir le mot de passe',
  'Please enter State' => 'Entrez l\'état',
  'Please enter Street Address' => 'Entrez le nom de la rue',
  'Please enter ZIP code' => 'Entrez le code postal',
  'Please enter a valid e-mail address' => 'Entrez une adresse email valide',
  'Please enter credit card holder first name' => 'Entrez le prénom du propriétaire de la carte',
  'Please enter credit card holder last name' => 'Veuillez entrer le nom de famille du propriétaire de la carte',
  'Please enter credit card holder name' => 'Entrez le nom du propriétaire de la carte',
  'Please enter housenumber' => 'Entrez le numéro de maison',
  'Please enter phone number' => 'Entrez un numéro de téléphone',
  'Please enter username and password' => 'Entrez nom d\'utilisateur et mot de passe',
  'Please enter valid Email' => 'Veuillez saisir une adresse email valide',
  'Please enter valid Login Name. It must contain at least %d characters' => 'Entrez un nom d\'utilisateur valide. Il doit contenir au moins %d caractères.',
  'Please enter valid Username. It must contain at least %d characters' => 'Veuillez saisir un nom d\'utilisateur valide. Il doit contenir au moins %d caractères.',
  'Please enter your First Name' => 'Veuillez saisir votre prénom',
  'Please enter your Last Name' => 'Veuillez saisir votre nom de famille',
  'Please enter your current password for validation' => 'Veuillez saisir votre mot de passe actuel pour valider',
  'Please login' => 'Veuillez vous connecter',
  'Please select a different log-in name' => 'Sélectionner un nom d\'utilisateur différent',
  'Please select payment system for payment' => 'Sélectionner le système de paiement',
  'Please wait %d seconds before next login attempt' => 'Attendez %d secondes avec de vous connecter à nouveau',
  'Plugin [%s] is not configured' => 'Le plugin [%s] n\'est pas configuré',
  'Prev' => 'Préc',
  'Price' => 'Prix',
  'Product' => 'Produit',
  'Product(s) to display' => 'Produit(s) à afficher',
  'Qty' => 'Qté',
  'Quantity' => 'Quantité',
  'Quick Order' => 'Commande rapide',
  'Re-Open Ticket' => 'Réouvrir un ticket',
  'Record' => 'Enregistrement',
  'Records that match all these conditions' => 'Enregistrements qui correspondent à toutes ces conditions',
  'Reference number is:' => 'Le numéro de référence est',
  'Referred Affiliate' => 'Filiale',
  'Refresh' => 'Rafraîchir',
  'Register' => 'S\'enregistrer',
  'Remember my password?' => 'Se souvenir de mon mot de passe?',
  'Remove Users
when user record removed from aMember
must the related record be removed from %s' => 'Supprimer des utilisateurs
lorsque les enregistrements d\'un utilisateur sont supprimés
l\'enregistrement lié doit être supprimé de %s',
  'Reply' => 'Répondre',
  'Return' => 'Retour',
  'Return and try again' => 'Retourner et réessayer',
  'Return to log-in page' => 'Retourner à la page de connexion',
  'Review your affiliate statistics' => 'Revoir vos statistiques affiliées',
  'Review/Pay Affiliate Commission' => 'Revoir/Commission affiliée',
  'Run Report' => 'Lancer le rapport',
  'Running %s' => 'Exécution de %s',
  'Save' => 'Enregistrer',
  'Save Profile' => 'Profil enregistré',
  'Search' => 'Rechercher',
  'Search Products' => 'Chercher les produits',
  'Security code is expired' => 'Le code de sécurité a expiré',
  'Security code is invalid' => 'Le code sécurité est invalide',
  'Select a condition to add into search' => 'Sélectionnez une condition à ajouter à la recherche',
  'Select card expiration date - month and year' => 'Sélectionner une date d\'expiration de la carte - mois et année',
  'Session expired, please enter username and password again' => 'Session expirée, entrez le nom d\'utilisateur et mot de passe à nouveau',
  'Shipping' => 'Expédition',
  'Shopping Cart' => 'Panier',
  'Sign-up' => 'Se connecter',
  'Sign-up - email verification' => 'Vérification d\'email',
  'Signup Form' => 'Formulaire d\'inscription',
  'Signup here' => 'Connectez-vous ici',
  'Simple Search Users' => 'Recherche d\'utilisateurs simple',
  'Sorry, it is impossible to use this payment method for this order. Please select another payment method' => 'Désolé, il est impossible d\'utiliser cette méthode de paiement pour cette commande. Veuillez choisir une autre méthode de paiement.',
  'Sorry, seems you have used wrong link' => 'Désolé, il semblerait que vous ayez utilisé le mauvais lien',
  'Source Code &mdash; Copy/Paste Into Your Website' => 'Code source &mdash; copier/coller sur votre site',
  'Start' => 'Début',
  'State' => 'État',
  'Street' => 'Rue',
  'Street Address' => 'Rue',
  'Subject' => 'Sujet',
  'Subject can not be empty' => 'Les sujets ne peuvent pas être vide',
  'Subscribe to Site Newsletters' => 'S\'abonner aux newsletters du site',
  'Subscribers' => 'Abonnés',
  'Subscription Terms' => 'Conditions d\'abonnement',
  'Subscription/Product Title' => 'Titre d\'abonnement/produit',
  'Subtotal' => 'Sous-total',
  'Target URL' => 'URL cible',
  'Tax' => 'Taxe',
  'Tax Amount' => 'Taxe',
  'Terms' => 'Conditions',
  'Test Settings' => 'Options de test',
  'Text has been entered incorrectly' => 'Le texte n\'a pas été saisi correctement',
  'Thank you for Signing up' => 'Merci de vous être enregistré',
  'The database has encountered a problem, please try again later.' => 'La base de données a rencontré un problème, recommencez plus tard.',
  'The information you have entered is incorrect' => 'Les informations entrées sont incorrectes',
  'The password should be at least %d characters long' => 'Le mot de passe doit être plus long que %d caractères.',
  'There are no confirmed payments for your account' => 'Il n\'y a pas de paiement confirmé pour votre compte',
  'This %s is blocked. Please contact site support to find out why' => 'Le %s est bloqué. Veuillez contacter le support du site pour découvrir pourquoi',
  'This coupon belongs to another customer' => 'Ce coupon appartient à un autre client',
  'This is a required field' => 'Ceci est un champ requis',
  'This page will be automatically refreshed within %s' => 'Cette page va être automatiquement rafraîchie dans %s',
  'This payment system could not handle payments in [%s] currency' => 'Ce système de paiement ne peut pas manipuler la devise [%s]',
  'This payment system could not handle zero-total invoices' => 'Ce système de paiement ne peut pas manipuler les factures avec un total de zéro.',
  'Ticket' => 'Ticket',
  'Ticket has been submited' => 'Le ticket a été soumis',
  'Tickets' => 'Tickets',
  'Title' => 'Titre',
  'To add fields into the form, move item from \'Available Bricks\' to \'Form Bricks\'.
To remove fields, move it back to \'Available Bricks\'.
To make form multi-page, insert \'PageSeparator\' item into the place where you want page to be split.' => 'Pour ajouter des champs au formulaires, déplacer des éléments de \'Briques disponibles\' à \'Former briques\'.
Pour supprimer des champs, redéplacez-les vers \'Briques disponibles\'.
Pour que le formulaire fasse plusieurs pages, insérez l\'élément \'PageSeparator\' à l\'endroit où vous voulez que les pages soient partagées.',
  'Total' => 'Total',
  'Try again' => 'Réessayer',
  'Unknown period unit: %s' => 'Unité de période inconnue: %s',
  'Unsubscribe from all e-mail messages' => 'Se désinscrire de tous les emails',
  'Unsubscription Confirmation' => 'Confirmation de la désinscription',
  'Update' => 'Mise à jour',
  'Update Credit Card Info' => 'Mise à jour des informations de carte de crédit',
  'Update your commissions payout info' => 'Mettre à jour vos informations de commissions sur le paiement',
  'Upgrade Subscription' => 'Mettre à jour l\'abonnement',
  'Use Database Connection other than configured for aMember' => 'Utiliser la connexion à la base de données autrement que configurée pour un membre',
  'Use another MySQL Db
use custom host, user, password for %s database connectionUsually you can leave this unchecked' => 'Utiliser une autre base de données MySQL
utiliser un hôte personnalisé, un utilisateur et mot de passe pour la connexion à la base de données %s. Vous pouvez généralement laisser ceci décoché',
  'Useful Links' => 'Liens utiles',
  'User Agreement' => 'Accord utilisateur',
  'User Info' => 'Informations de l\'utilisateur',
  'User Search' => 'Recherche d\'utilisateur',
  'User is not found in database' => 'L\'utilisateur n\'est pas trouvé dans la base de donnée',
  'Username' => 'Nom d\'utilisateur',
  'Username
you can choose new username here or keep it unchanged.
Username must be %d or more characters in length and may
only contain small letters, numbers, and underscore' => 'Nom d\'utilisateur
vous pouvez choisir un nouveau nom d\'utilisateur, ou conserver le même.
Le nom d\'utilisateur doit contenir %d caractères ou plus
et ne peut contenir que des lettres minuscules, chiffres et underscores',
  'Username %s has been taken by another user' => 'Le nom d\'utilisateur %s est déjà  utilisé.',
  'Username %s is already taken. Please choose another username' => 'Le nom d\'utilisateur %s est déjà pris. Veuillez choisir un autre nom d\'utilisateur',
  'Username [%s] does not exist in database' => 'Le nom d\'utilisateur [%s] n\'existe pas dans notre base de données',
  'Username contains invalid characters - please use digits and letters' => 'Le nom d\'utilisateur contient des caractères invalides - utilisez des nombres et des lettres',
  'Username contains invalid characters - please use digits, letters or spaces' => 'Le nom d\'utilisateur contient des caractères invalides - utilisez des chiffres, lettres ou espaces',
  'Users subscribed to Newsletter Threads #' => 'Utilisateurs abonnés aux sujets # de la lettre d\'informations',
  'Validate E-Mail Address by sending e-mail message with code' => 'Valider l\'adresse email en envoyant un email avec un code',
  'View Basket' => 'Voir le panier',
  'Week' => 'Semaine',
  'Wrong code or code expired - please start signup process again' => 'Code incorrect ou expiré - veuillez recommencer votre inscription',
  'Wrong parameters, error #1253' => 'Paramètres erronés, erreur #1253',
  'Wrong verification code' => 'Code vérification erroné',
  'Wrongly signed URL, please contact site admin' => 'URL mal signée, contactez l\'administrateur du site',
  'Year' => 'Année',
  'Years' => 'Années',
  'Yes, I want to cancel subscription' => 'Oui je veux annuler l\'abonnement',
  'Yes, continue' => 'Oui, continuer',
  'You can select more than one item - keep "Ctrl" key pressed' => 'Vous pouvez sélectionner plus d\'un objet - maintenez la touche "Ctrl" enfoncée',
  'You have no access to %s' => 'Vous n\'avez pas accès à %s',
  'You have no active subscriptions' => 'Vous n\'avez pas d\'abonnement actif',
  'You have no items in your basket - please add something to your basket before checkout' => 'Vous n\'avez aucun article dans votre panier - merci d\'ajouter quelque chose à votre panier avant la facturation',
  'You will be redirected to protected area' => 'Vous allez être redirigé vers une zone protégée',
  'Your Active Subscriptions' => 'Vos abonnements actifs',
  'Your Basket' => 'Votre panier',
  'Your Current Password
if you are changing password, please
 enter your current password for validation' => 'Votre mot de passe actuel
si vous changez de mot de passe, veuillez
entrer votre mot de passe actuel pour valider',
  'Your E-Mail Address
a confirmation email will be sent
to you at this address' => 'Votre adresse email
un email de confirmation vous sera envoyé
à cette adresse',
  'Your Membership Information' => 'Vos informations de membre',
  'Your email address has been changed' => 'Votre adresse mail à été changée',
  'Your message is too verbose' => 'Votre message est trop long',
  'Your password has been e-mailed to you' => 'Votre mot de passe vous a été envoyé par email',
  'Your password is too long' => 'Votre mot de passe est trop long',
  'Your payment is not yet confirmed by payment system. It may take several minutes to get confirmation of the payment.' => 'Votre paiement n\'a pas encore été confirmé par le système de paiement. Cela pourra prenrde encore plusieurs minutes.',
  'Your subject is too verbose' => 'Votre sujet est trop long',
  'ZIP' => 'Code postal',
  'ZIP Code' => 'Code postal',
  '[Select country]' => '[Sélectionner pays]',
  '[Select state]' => '[Sélectionner l\'état]',
  '_default_locale' => '_default_locale',
  'admin' => 'administrateur',
  'ago' => 'il y a',
  'banned' => 'banni',
  'commission found by next rules' => 'commission établie selon les règles suivantes',
  'customer / affiliate status' => 'statut client / affilié',
  'customer service phone number listed on back of your credit card' => 'Le numéro de téléphone du service clients est indiqué au dos de votre carte de crédit',
  'days' => 'jours',
  'displaying records %d-%d from %d' => 'enregistrements affichés %d-%d de %d',
  'email' => 'email',
  'filtered' => 'filtré',
  'for example: 1111-2222-3333-4444' => 'par exemple: 1111-2222-333-4444',
  'for international provinces outside of US & Canada include the province name here' => 'pour les provinces internationales en dehors des US et du Canada, inscrire le nom de la province ici',
  'hrs' => 'heures',
  'ip' => 'ip',
  'is required for Maestro/Solo/Switch credit cards only' => 'est requis pour les cartes de crédit Maestro/Solo/Switch seulement',
  'just now' => 'il y a un instant',
  'login' => 'nom d\'utilisateur$',
  'min' => 'min',
  'name of the bank which issued the credit card' => 'Nom de la banque qui a émis la carte de crédit',
  'no records' => 'aucun enregistrement',
  'of products' => 'de produits',
  'on %d-th day' => 'le %d-ième jour',
  'pay using wire transfer or by sending offline check' => 'payer en utilisant un virement bancaire ou en envoyant un chèque',
  'please select one' => 'Veuillez en choisir un',
  'return' => 'retour',
  'seconds' => 'secondes',
  'to order or renew subscription.' => 'pour commander ou renouveler l\'inscription',
  'use 4111-1111-1111-1111 for successful transaction' => 'utiliser 4111-1111-1111-1111 pour une transaction effectuée avec succès',
);
